import type { PracticeCase } from "../types";

export const abdominalPain: PracticeCase = {
  id: "abdominal-pain",
  title: "Abdominal pain",
  specialty: "Emergency medicine",
  blurb: "A 24-year-old woman with belly pain that moved to the right side.",
  patient: {
    name: "Emily Carter",
    age: 24,
    sex: "F",
    affect: "Lying still with her knees bent, wincing when she shifts.",
    opening: "My stomach really hurts, mostly on the right side now.",
    story: "It started as a dull ache around my belly button yesterday, and now it's sharp down on the lower right.",
  },
  door: { setting: "Urgent care", vitals: "BP 118/74, HR 102, RR 18, SpO2 99%, T 38.1 C", task: "Take a focused history, do a focused exam, then write a note with your differential and plan." },
  facts: {
    id: "Emily Carter. I'm 24.",
    onset: "It started yesterday evening, maybe 18 hours ago. It came on slowly.",
    duration: "It's been there ever since. It's getting worse.",
    location: "It started around my belly button, and now it's down here on the lower right.",
    migration: "Yes, it moved. It was around my belly button at first, then it went to the lower right this morning.",
    character: "Now it's sharp. At first it was more of a dull ache.",
    radiation: "It doesn't really go anywhere else.",
    severity: "Seven out of ten. Worse if I move.",
    timing: "It's constant.",
    aggravating: "Moving hurts, and the car ride over here was awful over the bumps. Coughing hurts too.",
    relieving: "Lying still helps a little. I took ibuprofen and it didn't really help.",
    associated: "I don't feel like eating, and I feel sick to my stomach. I threw up once this morning.",
    prior: "No, I've never had anything like this.",
    appetite: "I have no appetite at all. I skipped dinner and breakfast.",
    nausea: "I'm nauseous, and I threw up once this morning.",
    fever: "I felt warm and had chills last night.",
    bowel: "My last bowel movement was yesterday morning and it was normal. No diarrhea, no blood.",
    urinary: "No burning or anything when I pee.",
    vaginal: "No unusual discharge or bleeding.",
    lmp: "My last period started about seven weeks ago. I'm usually pretty regular, so I guess it's late.",
    sexual: "I have a boyfriend. We use condoms, but not every time.",
    pregnancy_possible: "I mean, I guess I could be. I haven't taken a test.",
    pmh: "I'm healthy. No medical problems.",
    psh: "No surgeries.",
    meds: "Just the ibuprofen this morning. I'm not on birth control pills.",
    allergies: "I'm allergic to penicillin. I get hives.",
    smoking: "No.",
    alcohol: "Socially, on weekends.",
    drugs: "No.",
    occupation: "I'm a graduate student.",
    living: "I live with a roommate.",
    family: "My mom had her gallbladder out. Nothing else I know of.",
    trauma: "No, I didn't get hurt.",
    concerns: "I have a big exam on Friday. I'm worried I'll need surgery.",
    empathy: "Thank you. It really hurts.",
    next: "Okay. Will I need surgery?",
  },
  topics: {
    migration: ["move", "moved", "moving around", "belly button", "started somewhere else", "change location", "shift"],
    vaginal: ["vaginal", "discharge", "spotting", "bleeding"],
    pregnancy_possible: ["could you be pregnant", "chance you could be pregnant", "possibility of pregnancy", "pregnancy test"],
  },
  cues: ["concerns"],
  exam: [
    { key: "vitals", label: "Check vitals", ask: "Let me check your vital signs.", finding: "T 38.1 C, HR 102, BP 118/74, RR 18, SpO2 99%.", match: ["vitals", "vital signs", "temperature", "blood pressure", "pulse"], required: true },
    { key: "abdomen", label: "Press on belly", ask: "I'd like to examine your abdomen.", finding: "Tender at McBurney's point with voluntary guarding. Rebound tenderness in the right lower quadrant. Bowel sounds present.", match: ["abdomen", "belly", "stomach", "tummy", "abdominal"], required: true },
    { key: "rovsing", label: "Special signs (Rovsing, psoas)", ask: "I'm going to press on the left side and check a few special signs.", finding: "Positive Rovsing sign. Positive psoas sign on the right.", match: ["rovsing", "psoas", "obturator", "special", "left side"] },
    { key: "cva", label: "Tap on back (CVA)", ask: "I'm going to tap on your back over the kidneys.", finding: "No costovertebral angle tenderness.", match: ["cva", "costovertebral", "flank", "kidneys", "tap on your back"] },
    { key: "pelvic", label: "Pelvic exam", ask: "I'd like to do a pelvic exam, with a chaperone.", finding: "Deferred to the ED team. No cervical motion tenderness reported on their exam.", match: ["pelvic", "cervical motion", "vaginal exam"] },
  ],
  checklist: [
    { id: "onset", label: "Onset and progression", topics: ["onset", "duration"], weight: 1, ask: "When did the pain start, and has it changed?" },
    { id: "location", label: "Location", topics: ["location"], weight: 1, ask: "Where exactly is the pain?" },
    { id: "migration", label: "Migration from belly button to right lower side", topics: ["migration", "location"], weight: 2, ask: "Did the pain start somewhere else and move?" },
    { id: "character", label: "Quality", topics: ["character"], weight: 1, ask: "What does the pain feel like?" },
    { id: "severity", label: "Severity", topics: ["severity"], weight: 1, ask: "How bad is it from 0 to 10?" },
    { id: "aggravating", label: "Worse with movement", topics: ["aggravating", "relieving"], weight: 1, ask: "What makes it better or worse?" },
    { id: "gi", label: "Appetite, nausea, vomiting", topics: ["appetite", "nausea", "associated"], weight: 2, ask: "Any nausea, vomiting, or loss of appetite?" },
    { id: "fever", label: "Fever", topics: ["fever"], weight: 1, ask: "Have you had any fever or chills?" },
    { id: "bowel", label: "Bowel changes", topics: ["bowel"], weight: 1, ask: "Any diarrhea, constipation, or blood in your stool?" },
    { id: "urinary", label: "Urinary symptoms", topics: ["urinary"], weight: 1, ask: "Any burning with urination?" },
    { id: "lmp", label: "Last menstrual period", topics: ["lmp", "pregnancy_possible"], weight: 3, redFlag: true, ask: "When was your last period? Is there any chance you could be pregnant?" },
    { id: "sexual", label: "Sexual history", topics: ["sexual", "pregnancy_possible"], weight: 2, redFlag: true, ask: "Are you sexually active, and do you use protection?" },
    { id: "vaginal", label: "Vaginal bleeding or discharge", topics: ["vaginal"], weight: 1, ask: "Any vaginal bleeding or discharge?" },
    { id: "pmh", label: "Past medical and surgical history", topics: ["pmh", "psh"], weight: 1, ask: "Any medical problems or surgeries?" },
    { id: "meds", label: "Medications", topics: ["meds"], weight: 1, ask: "Do you take any medicines?" },
    { id: "allergies", label: "Allergies (penicillin)", topics: ["allergies"], weight: 2, redFlag: true, ask: "Any allergies to medicines?" },
  ],
  note: {
    facts: [
      { id: "cc", label: "RLQ abdominal pain for 18 hours", any: ["rlq", "right lower quadrant", "right lower", "abdominal pain"], kind: "pos", weight: 2 },
      { id: "migration", label: "Periumbilical pain that migrated to RLQ", any: ["periumbilical", "belly button", "migrat", "umbilic"], kind: "pos", topic: "migration", weight: 2 },
      { id: "anorexia", label: "Anorexia", any: ["anorexia", "appetite"], kind: "pos", topic: "appetite", weight: 1 },
      { id: "vomit", label: "Nausea and one episode of vomiting", any: ["nausea", "vomit", "emesis"], kind: "pos", topic: "nausea", weight: 1 },
      { id: "fever", label: "Subjective fever and chills", any: ["fever", "chills", "febrile"], kind: "pos", topic: "fever", weight: 1 },
      { id: "lmp", label: "LMP 7 weeks ago, late", any: ["lmp", "last menstrual", "period", "weeks ago"], kind: "hx", topic: "lmp", weight: 2 },
      { id: "sexual", label: "Sexually active, inconsistent condoms", any: ["sexually active", "condom"], kind: "hx", topic: "sexual", weight: 1 },
      { id: "allergy", label: "Penicillin allergy (hives)", any: ["penicillin", "pcn"], kind: "hx", topic: "allergies", weight: 1 },
      { id: "no_urinary", label: "Denies urinary symptoms", any: ["dysuria", "urinary"], kind: "neg", topic: "urinary", weight: 1 },
      { id: "abd", label: "McBurney tenderness with rebound", any: ["mcburney", "rebound", "guarding", "rlq tender"], kind: "exam", exam: "abdomen", weight: 2 },
      { id: "rovsing", label: "Positive Rovsing and psoas signs", any: ["rovsing", "psoas"], kind: "exam", exam: "rovsing", weight: 1 },
    ],
    differential: [
      { dx: "Acute appendicitis", any: ["appendicitis", "appy"], leading: true },
      { dx: "Ectopic pregnancy", any: ["ectopic"] },
      { dx: "Ovarian torsion", any: ["torsion"] },
      { dx: "Pelvic inflammatory disease or tubo-ovarian abscess", any: ["pid", "pelvic inflammatory", "tubo ovarian", "toa"] },
      { dx: "Kidney stone or pyelonephritis", any: ["nephrolith", "kidney stone", "pyelo", "ureter"] },
    ],
    plan: [
      { label: "Pregnancy test first", any: ["hcg", "pregnancy test", "beta hcg", "upt"], weight: 3 },
      { label: "CBC and labs", any: ["cbc", "white count", "wbc", "labs", "cmp", "bmp"], weight: 1 },
      { label: "Urinalysis", any: ["urinalysis", "ua"], weight: 1 },
      { label: "Imaging (ultrasound or CT)", any: ["ultrasound", "ct", "imaging"], weight: 2 },
      { label: "Surgery consult", any: ["surgery", "surgical consult", "general surgery"], weight: 2 },
      { label: "NPO, fluids, pain control", any: ["npo", "iv fluids", "fluids", "analgesia", "pain control"], weight: 1 },
    ],
    contradictions: [{ label: "Wrote no drug allergies, but she is allergic to penicillin", any: ["nkda", "no known drug allergies", "no allergies"] }],
  },
  pimp: [
    { q: "Why does a pregnancy test come first in this patient?", any: ["ectopic", "imaging", "radiation", "ct"], answer: "Ectopic pregnancy is a can't-miss diagnosis, and a positive test changes which imaging you choose." },
    { q: "What's it called when pressing the left lower belly causes pain on the right?", any: ["rovsing"], answer: "Rovsing sign." },
    { q: "Her penicillin allergy matters. Why?", any: ["antibiotic", "cephalosporin", "cefoxitin", "ceftriaxone", "cross", "prophylaxis"], answer: "She'll likely need antibiotics before surgery, so you choose one that's safe with a penicillin allergy." },
  ],
  model: "Ms. Carter is a 24-year-old woman with no medical history who presents with 18 hours of abdominal pain that began around the umbilicus and migrated to the right lower quadrant, with anorexia, nausea, one episode of vomiting, and subjective fever. Her last menstrual period was 7 weeks ago, and she is sexually active with inconsistent condom use. She denies urinary symptoms and vaginal discharge. She is allergic to penicillin. She is febrile to 38.1 with McBurney point tenderness, rebound, and positive Rovsing and psoas signs. The leading diagnosis is acute appendicitis, but ectopic pregnancy must be ruled out first. I'd get a pregnancy test, CBC, urinalysis, and ultrasound or CT depending on the result, keep her NPO, and consult surgery.",
};
