import type { PracticeCase } from "../types";

export const chestPain: PracticeCase = {
  id: "chest-pain",
  title: "Chest pain",
  specialty: "Emergency medicine",
  blurb: "A 58-year-old man with chest pressure that won't go away.",
  patient: {
    name: "Robert Alvarez",
    age: 58,
    sex: "M",
    affect: "Anxious and a little sweaty, rubbing the center of his chest.",
    opening: "I've got this pressure in my chest, and it just won't go away.",
    story: "It's like somebody's sitting on my chest. It started a couple of hours ago and it hasn't let up.",
  },
  door: { setting: "Emergency department", vitals: "BP 158/94, HR 104, RR 20, SpO2 96% on room air, T 37.0 C", task: "Take a focused history, do a focused exam, then write a note with your differential and plan." },
  facts: {
    id: "I'm Robert Alvarez. I'm 58.",
    onset: "It started about two hours ago. I was carrying groceries up the stairs.",
    duration: "It's been there the whole two hours. It hasn't gone away at all.",
    location: "Right here, in the middle of my chest, behind the breastbone.",
    character: "It's a pressure, like a heavy weight. Not really sharp.",
    radiation: "Yeah, it goes into my left arm, and kind of up into my jaw.",
    severity: "Right now it's about an eight out of ten.",
    timing: "It's constant. It doesn't come and go.",
    aggravating: "It got worse when I was climbing the stairs. Breathing doesn't change it.",
    exertion: "Yes. The last couple of weeks I get a little tight in the chest walking up stairs, but it always went away when I stopped. This time it didn't.",
    relieving: "Nothing helps. I sat down and rested, and it's still there.",
    associated: "I feel sweaty, a bit sick to my stomach, and a little short of breath.",
    prior: "Not like this. Just those little tight spells on the stairs lately.",
    sweating: "Yes, I've been sweating. My shirt's soaked.",
    nausea: "I feel queasy, but I haven't thrown up.",
    sob: "A little short of breath, yeah.",
    palpitations: "No, my heart isn't racing that I can tell.",
    dizziness: "No, I haven't passed out.",
    fever: "No fever.",
    cough: "No cough.",
    swelling: "No, my legs aren't swollen.",
    pmh: "I have high blood pressure and high cholesterol.",
    risk: "No diabetes that I know of.",
    chest_pain: "It's a heavy pressure right in the middle of my chest. It's been there about two hours.",
    psh: "Just my knee scoped years ago.",
    meds: "Lisinopril for blood pressure and atorvastatin, but honestly I skip the cholesterol pill a lot.",
    allergies: "No allergies.",
    smoking: "I smoke about a pack a day. Have for 30 years.",
    alcohol: "A couple of beers on the weekend.",
    drugs: "No, no drugs. Never used cocaine or anything like that.",
    occupation: "I drive a delivery truck.",
    living: "I live with my wife.",
    family: "My father had a heart attack when he was 52. He died from it.",
    trauma: "No, I didn't hurt myself.",
    clot: "No recent long trips or surgery, and no leg pain or swelling.",
    concerns: "I'm scared it's my heart. My dad died of a heart attack.",
    empathy: "Thanks. I'm just really scared.",
    next: "Okay. Whatever you need to do.",
  },
  topics: {
    exertion: ["exertion", "exert", "stairs", "walking", "exercise", "activity", "climb"],
    risk: ["diabetes", "cholesterol", "blood pressure", "hypertension", "risk factors"],
    clot: ["long trip", "long flight", "travel", "recent surgery", "leg pain", "calf", "blood clot", "clots", "immobil"],
  },
  cues: ["concerns", "family"],
  exam: [
    { key: "vitals", label: "Check vitals", ask: "Let me check your vital signs.", finding: "BP 158/94 right arm, 156/92 left arm. HR 104, RR 20, SpO2 96%.", match: ["vitals", "vital signs", "blood pressure", "pulse", "both arms"], required: true },
    { key: "heart", label: "Listen to heart", ask: "I'd like to listen to your heart.", finding: "Tachycardic, regular rhythm. Normal S1 and S2. No murmurs, rubs, or gallops.", match: ["heart", "cardiac", "chest"], required: true },
    { key: "lungs", label: "Listen to lungs", ask: "I'd like to listen to your lungs.", finding: "Clear to auscultation bilaterally. No crackles or wheezes.", match: ["lungs", "lung", "breathing"], required: true },
    { key: "pulses", label: "Check pulses in both arms", ask: "Let me feel the pulses in both of your arms.", finding: "Radial pulses 2+ and equal bilaterally.", match: ["pulses", "radial", "arms"] },
    { key: "legs", label: "Look at legs", ask: "Let me look at your legs.", finding: "No calf tenderness or swelling. No edema.", match: ["legs", "calves", "calf", "ankles", "edema"] },
  ],
  checklist: [
    { id: "onset", label: "Onset and what he was doing", topics: ["onset"], weight: 2, ask: "When did this start, and what were you doing?" },
    { id: "location", label: "Location", topics: ["location"], weight: 1, ask: "Can you point to where you feel it?" },
    { id: "character", label: "Quality of the pain", topics: ["character", "open"], weight: 1, ask: "What does it feel like?" },
    { id: "radiation", label: "Radiation to arm or jaw", topics: ["radiation"], weight: 2, redFlag: true, ask: "Does the pain go anywhere else, like your arm, jaw, or back?" },
    { id: "severity", label: "Severity", topics: ["severity"], weight: 1, ask: "On a scale of 0 to 10, how bad is it?" },
    { id: "timing", label: "Constant or comes and goes", topics: ["timing", "duration"], weight: 1, ask: "Is it constant, or does it come and go?" },
    { id: "exertion", label: "Exertional pattern", topics: ["exertion", "aggravating", "prior"], weight: 2, redFlag: true, ask: "Have you had chest tightness with exertion, like climbing stairs?" },
    { id: "relieving", label: "What makes it better", topics: ["relieving"], weight: 1, ask: "Does anything make it better, like rest?" },
    { id: "associated", label: "Sweating, nausea, shortness of breath", topics: ["associated", "sweating", "nausea", "sob"], weight: 2, redFlag: true, ask: "Any sweating, nausea, or shortness of breath with it?" },
    { id: "risk", label: "Cardiac risk factors", topics: ["pmh", "risk"], weight: 2, ask: "Do you have high blood pressure, diabetes, or high cholesterol?" },
    { id: "meds", label: "Medications and adherence", topics: ["meds"], weight: 1, ask: "What medicines do you take, and do you take them every day?" },
    { id: "allergies", label: "Allergies", topics: ["allergies"], weight: 1, ask: "Any allergies to medicines?" },
    { id: "smoking", label: "Smoking", topics: ["smoking"], weight: 2, ask: "Do you smoke?" },
    { id: "drugs", label: "Cocaine or stimulant use", topics: ["drugs"], weight: 1, redFlag: true, ask: "Do you use any drugs, like cocaine?" },
    { id: "family", label: "Family history of early heart disease", topics: ["family"], weight: 2, redFlag: true, ask: "Does anyone in your family have heart disease?" },
    { id: "clot", label: "Clot risk (travel, surgery, leg swelling)", topics: ["clot", "swelling"], weight: 1, ask: "Any recent long trips, surgery, or leg swelling?" },
  ],
  note: {
    facts: [
      { id: "cc", label: "Chest pressure for 2 hours", any: ["chest pressure", "chest pain", "chest tightness", "substernal"], kind: "pos", weight: 2 },
      { id: "radiation", label: "Radiation to left arm and jaw", any: ["left arm", "jaw", "radiat"], kind: "pos", topic: "radiation", weight: 2 },
      { id: "exertion", label: "Exertional onset and recent exertional tightness", any: ["exertion", "stairs", "exertional", "climbing"], kind: "pos", topic: "exertion", weight: 2 },
      { id: "diaphoresis", label: "Diaphoresis", any: ["diaphore", "sweat"], kind: "pos", topic: "sweating", weight: 1 },
      { id: "nausea", label: "Nausea", any: ["nausea", "nauseous", "queasy"], kind: "pos", topic: "nausea", weight: 1 },
      { id: "risk", label: "HTN and hyperlipidemia", any: ["hypertension", "htn", "hyperlipidemia", "hld", "cholesterol", "high blood pressure"], kind: "hx", topic: "pmh", weight: 1 },
      { id: "smoking", label: "30 pack-year smoker", any: ["smok", "pack", "tobacco"], kind: "hx", topic: "smoking", weight: 1 },
      { id: "family", label: "Father with MI at 52", any: ["father", "family history", "fhx", "dad"], kind: "hx", topic: "family", weight: 1 },
      { id: "no_cocaine", label: "Denies cocaine", any: ["cocaine", "no drugs", "denies drug", "illicit"], kind: "neg", topic: "drugs", weight: 1 },
      { id: "heart", label: "Heart exam: tachycardic, no murmur", any: ["murmur", "s1", "rrr", "regular rhythm", "tachycardic"], kind: "exam", exam: "heart", weight: 1 },
      { id: "lungs", label: "Lungs clear", any: ["clear to auscultation", "lungs clear", "cta", "no crackles"], kind: "exam", exam: "lungs", weight: 1 },
      { id: "pulses", label: "Equal pulses in both arms", any: ["pulses equal", "equal pulses", "equal bilaterally", "symmetric pulses", "radial pulses"], kind: "exam", exam: "pulses", weight: 1 },
    ],
    differential: [
      { dx: "Acute coronary syndrome", any: ["acs", "acute coronary", "nstemi", "stemi", "myocardial infarction", "unstable angina", "heart attack", "mi"], leading: true },
      { dx: "Aortic dissection", any: ["dissection"] },
      { dx: "Pulmonary embolism", any: ["pulmonary embol", "pe"] },
      { dx: "Stable angina", any: ["stable angina", "angina"] },
      { dx: "GERD or esophageal spasm", any: ["gerd", "reflux", "esophag"] },
    ],
    plan: [
      { label: "ECG right away", any: ["ecg", "ekg", "electrocardiogram"], weight: 3 },
      { label: "Troponin", any: ["troponin", "trop", "cardiac enzymes"], weight: 2 },
      { label: "Aspirin", any: ["aspirin", "asa"], weight: 2 },
      { label: "Cardiology or cath lab", any: ["cardiology", "cath", "catheterization", "pci"], weight: 1 },
      { label: "Chest X-ray", any: ["chest x-ray", "chest xray", "cxr", "x-ray"], weight: 1 },
    ],
    contradictions: [{ label: "Pain described as pleuritic or reproducible, which he did not say", any: ["pleuritic", "reproducible", "worse with breathing"] }],
  },
  pimp: [
    { q: "What's the first test you'd get, and how fast?", any: ["ecg", "ekg", "electrocardiogram"], answer: "A 12-lead ECG within 10 minutes of arrival." },
    { q: "What medicine would you give right now, and how?", any: ["aspirin", "asa"], answer: "Aspirin 162 to 325 mg, chewed, unless there's a true allergy." },
    { q: "What exam finding would make you worry about aortic dissection?", any: ["unequal", "different", "difference", "asymmetric", "pulse deficit", "both arms", "blood pressure in both", "widened mediastinum"], answer: "A blood pressure or pulse difference between the arms, or a new aortic regurgitation murmur." },
  ],
  model: "Mr. Alvarez is a 58-year-old man with hypertension, hyperlipidemia, and a 30 pack-year smoking history who presents with 2 hours of constant substernal chest pressure that began while climbing stairs, radiates to his left arm and jaw, and is associated with diaphoresis, nausea, and mild shortness of breath. He reports two weeks of exertional chest tightness relieved by rest. His father died of a heart attack at 52. He denies cocaine use. He is tachycardic at 104 and hypertensive, with equal pulses in both arms and clear lungs. My leading concern is acute coronary syndrome. I'd get an ECG within 10 minutes, troponins, give aspirin, and involve cardiology.",
};
