import type { PracticeCase } from "../types";

export const depression: PracticeCase = {
  id: "depression-screen",
  title: "Low mood",
  specialty: "Psychiatry and primary care",
  blurb: "A 29-year-old man who hasn't felt like himself since losing his job.",
  patient: {
    name: "Marcus Reed",
    age: 29,
    sex: "M",
    affect: "Quiet, looks at the floor, answers slowly.",
    opening: "I just haven't been myself lately. My girlfriend made me come in.",
    story: "I don't know. Everything feels heavy. I don't really want to do anything anymore.",
  },
  door: { setting: "Primary care clinic", vitals: "BP 124/78, HR 70, RR 14, T 36.8 C, weight down 8 lb since last visit", task: "Take a focused history including a safety assessment, then write a note with your assessment and plan." },
  facts: {
    id: "Marcus Reed. I'm 29.",
    onset: "About two months ago. Right after I got laid off.",
    duration: "Pretty much every day for the last two months.",
    trigger: "I lost my job in August. I'd been there six years.",
    mood: "I feel down most of the day, almost every day. Kind of empty.",
    anhedonia: "I used to play basketball with my friends three times a week. I haven't gone in over a month. Nothing sounds fun.",
    sleep: "I wake up at like 4 in the morning and can't get back to sleep.",
    appetite: "I'm not really hungry. I've lost some weight.",
    weight: "About eight pounds, I think.",
    fatigue: "I'm tired all the time, even though I'm not doing anything.",
    concentration: "I can't focus. I read the same page over and over.",
    guilt: "I feel like a failure. Like I let my girlfriend down.",
    suicide: "Sometimes I think it'd be easier if I just didn't wake up. I haven't done anything about it.",
    plan: "No, I don't have a plan. I wouldn't actually do anything.",
    intent: "No. I don't want to die, I just want this to stop.",
    firearm: "There's a hunting rifle at my dad's house. I don't have one at my place.",
    prior_attempt: "No, never. I've never tried to hurt myself.",
    mania: "No, nothing like that. I've never had times where I didn't need sleep or felt on top of the world.",
    psychosis: "No, I don't hear voices or anything like that.",
    anxiety: "I worry about money a lot, but I wouldn't say panic attacks.",
    alcohol: "More than I used to. Four or five beers most nights, to fall asleep.",
    drugs: "I smoke weed sometimes. Maybe once a week.",
    smoking: "No cigarettes.",
    pmh: "Nothing. I've always been healthy.",
    psych_history: "No. I've never seen anybody for my mental health.",
    meds: "No medicines.",
    allergies: "No allergies.",
    occupation: "I was a warehouse supervisor until August.",
    living: "I live with my girlfriend. She's been really supportive.",
    family: "My mom has depression. She takes something for it.",
    thyroid: "No, I don't feel hot or cold all the time. No neck swelling.",
    concerns: "I don't want to be on pills forever. And I don't want people to think I'm crazy.",
    empathy: "Thanks. It's hard to talk about.",
    next: "Okay. I'll try.",
  },
  topics: {
    trigger: ["what happened", "anything happen", "changed", "happened recently", "anything change", "stressor", "stress", "life changes", "going on in your life", "job"],
    concentration: ["concentrat", "focus", "attention", "memory"],
    guilt: ["guilt", "guilty", "worthless", "failure", "blame yourself"],
    plan: ["plan", "how would you", "thought about how", "method"],
    intent: ["intent", "intend", "act on", "going to do it", "want to die"],
    firearm: ["gun", "guns", "firearm", "firearms", "weapon", "rifle", "access to"],
    prior_attempt: ["attempt", "tried to hurt", "tried to kill", "before tried", "ever tried"],
    mania: ["mania", "manic", "on top of the world", "don't need sleep", "didn't need sleep", "racing thoughts", "high energy", "euphori", "bipolar"],
    psychosis: ["voices", "hallucinat", "seeing things", "paranoi"],
    anxiety: ["worry", "panic", "anxious", "anxiety"],
    psych_history: ["mental health", "psychiatrist", "therapist", "counseling", "therapy", "psych history", "seen anyone"],
    thyroid: ["thyroid", "hot or cold", "heat intolerance", "cold intolerance"],
  },
  cues: ["trigger", "suicide", "guilt", "concerns"],
  exam: [
    { key: "vitals", label: "Check vitals", ask: "Let me check your vital signs.", finding: "BP 124/78, HR 70, T 36.8 C. Weight 8 lb lower than 4 months ago.", match: ["vitals", "vital signs", "blood pressure", "weight"], required: true },
    { key: "mse", label: "Mental status exam", ask: "I'm going to note how you're doing today, your mood and thinking.", finding: "Casually dressed, poor eye contact, psychomotor slowing. Speech slow and soft. Mood 'down', affect constricted. Thought process linear. Passive death wish without plan or intent. No hallucinations. Insight and judgment fair.", match: ["mental status", "mse", "appearance", "affect", "mood and thinking"], required: true },
    { key: "thyroid", label: "Feel thyroid", ask: "Let me feel your thyroid.", finding: "Thyroid normal size, no nodules.", match: ["thyroid", "neck"] },
  ],
  checklist: [
    { id: "mood", label: "Depressed mood and duration", topics: ["mood", "duration", "onset"], weight: 2, ask: "How has your mood been, and for how long?" },
    { id: "anhedonia", label: "Loss of interest", topics: ["anhedonia"], weight: 2, ask: "Are you still enjoying the things you used to?" },
    { id: "sleep", label: "Sleep", topics: ["sleep"], weight: 1, ask: "How are you sleeping?" },
    { id: "appetite", label: "Appetite and weight", topics: ["appetite", "weight"], weight: 1, ask: "Any change in appetite or weight?" },
    { id: "energy", label: "Energy and concentration", topics: ["fatigue", "concentration"], weight: 1, ask: "How are your energy and concentration?" },
    { id: "guilt", label: "Guilt or worthlessness", topics: ["guilt"], weight: 1, ask: "Do you feel guilty or like a failure?" },
    { id: "si", label: "Thoughts of suicide", topics: ["suicide"], weight: 3, redFlag: true, ask: "Have you had thoughts of hurting yourself or ending your life?" },
    { id: "plan", label: "Plan and intent", topics: ["plan", "intent"], weight: 2, redFlag: true, ask: "Have you thought about how you would do it, or do you intend to act on it?" },
    { id: "firearm", label: "Access to firearms", topics: ["firearm"], weight: 2, redFlag: true, ask: "Do you have access to a gun?" },
    { id: "attempt", label: "Past attempts", topics: ["prior_attempt"], weight: 1, redFlag: true, ask: "Have you ever tried to hurt yourself before?" },
    { id: "mania", label: "Screen for mania", topics: ["mania"], weight: 2, redFlag: true, ask: "Have you ever had times when you felt on top of the world and didn't need sleep?" },
    { id: "trigger", label: "Stressors", topics: ["trigger", "occupation"], weight: 1, ask: "Has anything changed or happened recently?" },
    { id: "substances", label: "Alcohol and drugs", topics: ["alcohol", "drugs"], weight: 2, ask: "How much do you drink, and do you use any drugs?" },
    { id: "support", label: "Support at home", topics: ["living"], weight: 1, ask: "Who do you have for support?" },
    { id: "family", label: "Family psychiatric history", topics: ["family"], weight: 1, ask: "Does anyone in your family have depression?" },
  ],
  note: {
    facts: [
      { id: "cc", label: "Depressed mood for 2 months", any: ["depressed mood", "low mood", "feeling down", "down most", "depress"], kind: "pos", topic: "mood", weight: 2 },
      { id: "anhedonia", label: "Anhedonia (stopped basketball)", any: ["anhedonia", "basketball", "loss of interest", "lost interest"], kind: "pos", topic: "anhedonia", weight: 2 },
      { id: "sleep", label: "Early morning awakening", any: ["early morning", "insomnia", "4 am", "wakes early", "sleep"], kind: "pos", topic: "sleep", weight: 1 },
      { id: "weight", label: "Poor appetite, 8 lb weight loss", any: ["weight loss", "8 lb", "8 pound", "appetite"], kind: "pos", topic: "appetite", weight: 1 },
      { id: "si", label: "Passive death wish, no plan or intent", any: ["passive", "suicidal ideation", "si", "death wish", "not wake up", "didn't wake up"], kind: "pos", topic: "suicide", weight: 3 },
      { id: "no_plan", label: "Denies plan or intent", any: ["no plan", "denies plan", "without plan", "no intent", "denies intent"], kind: "neg", topic: "plan", weight: 2 },
      { id: "firearm", label: "Rifle at father's home, none at his", any: ["rifle", "firearm", "gun"], kind: "hx", topic: "firearm", weight: 2 },
      { id: "no_mania", label: "Denies history of mania", any: ["mania", "manic", "bipolar"], kind: "neg", topic: "mania", weight: 1 },
      { id: "alcohol", label: "4 to 5 beers nightly", any: ["beer", "alcohol", "etoh", "drinks"], kind: "hx", topic: "alcohol", weight: 1 },
      { id: "trigger", label: "Job loss 2 months ago", any: ["job loss", "laid off", "lost his job", "unemploy"], kind: "hx", topic: "trigger", weight: 1 },
      { id: "family", label: "Mother with depression", any: ["mother", "family history", "mom"], kind: "hx", topic: "family", weight: 1 },
      { id: "mse", label: "Psychomotor slowing, constricted affect", any: ["psychomotor", "constricted", "flat affect", "poor eye contact"], kind: "exam", exam: "mse", weight: 1 },
    ],
    differential: [
      { dx: "Major depressive disorder", any: ["major depressi", "mdd", "depressive disorder", "depression"], leading: true },
      { dx: "Adjustment disorder", any: ["adjustment"] },
      { dx: "Alcohol use disorder", any: ["alcohol use", "aud"] },
      { dx: "Bipolar disorder", any: ["bipolar"] },
      { dx: "Hypothyroidism", any: ["hypothyroid", "thyroid"] },
    ],
    plan: [
      { label: "Safety plan and crisis line (988)", any: ["safety plan", "988", "crisis line", "crisis"], weight: 3 },
      { label: "Firearm safety or means restriction", any: ["firearm", "gun", "means restriction", "lethal means", "rifle"], weight: 2 },
      { label: "PHQ-9", any: ["phq"], weight: 1 },
      { label: "Start an SSRI", any: ["ssri", "sertraline", "escitalopram", "fluoxetine", "citalopram", "antidepressant"], weight: 2 },
      { label: "Therapy referral", any: ["therapy", "cbt", "counsel", "psychotherap", "behavioral health"], weight: 2 },
      { label: "Cut back on alcohol", any: ["alcohol", "drinking", "audit"], weight: 1 },
      { label: "Close follow-up (1 to 2 weeks)", any: ["follow up", "follow-up", "1 week", "2 weeks", "two weeks", "one week"], weight: 1 },
    ],
    contradictions: [{ label: "Wrote denies suicidal thoughts, but he has a passive death wish", any: ["denies si", "denies suicidal", "no suicidal", "no si"] }],
  },
  pimp: [
    { q: "How many symptoms, and for how long, do you need to call it major depression?", any: ["5", "five", "two weeks", "2 weeks"], answer: "At least 5 of 9 symptoms, including low mood or loss of interest, for at least 2 weeks." },
    { q: "What must you screen for before starting an antidepressant?", any: ["bipolar", "mania", "manic"], answer: "A history of mania or hypomania, because an antidepressant alone can trigger mania in bipolar disorder." },
    { q: "What number can he call or text any time in a crisis?", any: ["988"], answer: "988, the Suicide and Crisis Lifeline." },
  ],
  model: "Mr. Reed is a 29-year-old man with no psychiatric history who presents with 2 months of depressed mood after losing his job, with anhedonia, early morning awakening, poor appetite with an 8 lb weight loss, fatigue, poor concentration, and guilt. He reports a passive wish not to wake up, without plan, intent, or past attempts. There is a rifle at his father's house but none at his home. He denies any history of mania or psychosis. He drinks 4 to 5 beers most nights. His mother has depression. On exam he has psychomotor slowing and a constricted affect. This is most consistent with major depressive disorder, single episode, moderate. I'd make a safety plan with 988, talk about keeping firearms away, do a PHQ-9, start sertraline, refer to therapy, address his drinking, and see him in 2 weeks.",
};
