import type { PracticeCase } from "../types";

export const diabetes: PracticeCase = {
  id: "diabetes-follow-up",
  title: "Diabetes follow-up",
  specialty: "Primary care",
  blurb: "A 61-year-old woman whose A1c went up to 8.9.",
  patient: {
    name: "Linda Brooks",
    age: 61,
    sex: "F",
    affect: "Friendly but a little embarrassed about her numbers.",
    opening: "I'm here for my diabetes check. I know my sugar number went up.",
    story: "I've been trying, but it's been hard to keep up with everything the last few months.",
  },
  door: { setting: "Primary care clinic, scheduled follow-up", vitals: "BP 142/88, HR 76, BMI 33. A1c today 8.9% (was 7.6% six months ago).", task: "Take a focused history, do a focused exam, then write a note with your assessment and plan." },
  facts: {
    id: "Linda Brooks. I'm 61.",
    onset: "I was diagnosed about eight years ago. The last six months have been harder.",
    adherence: "To be honest, I skip the evening metformin most days. It gives me diarrhea and an upset stomach.",
    glucose: "I check sometimes. Mornings are usually around 170 to 190.",
    hypoglycemia: "No, I haven't had any lows. No shaky or sweaty spells.",
    diet: "I drink a lot of regular soda, maybe three cans a day. And I eat out a lot since my husband passed.",
    exercise_hx: "Not really. My knees hurt.",
    neuro: "My feet tingle and feel numb at night, both of them. It's been a few months.",
    foot: "No sores or cuts on my feet that I've seen. I don't really check them.",
    vision: "Sometimes my vision is a little blurry. I haven't seen the eye doctor in about two years.",
    urinary: "I've been peeing more than usual, and I'm thirsty a lot.",
    thirst: "Yes, I'm thirsty all the time, and I'm up at night to pee.",
    chest_pain: "No chest pain, even when I walk.",
    sob: "No trouble breathing.",
    weight: "I've gained a few pounds this year.",
    fatigue: "I'm a little more tired than usual.",
    mood: "It's been a hard year since my husband died, but I'm okay. I'm sleeping alright.",
    pmh: "Diabetes, high blood pressure, and my knees.",
    psh: "I had my gallbladder out.",
    meds: "Metformin 1000 twice a day, but like I said, I skip the evening one. And lisinopril 10 for blood pressure.",
    allergies: "Sulfa drugs give me a rash.",
    smoking: "I quit smoking 15 years ago.",
    alcohol: "Maybe a glass of wine on holidays.",
    drugs: "No.",
    occupation: "I drive a school bus.",
    living: "I live alone now. My husband died last year.",
    family: "My mother had diabetes and lost a toe to it.",
    concerns: "I'm worried I'll end up on insulin shots like my mom. Or lose my feet like she did.",
    empathy: "Thank you. It's been a hard year.",
    next: "Okay. As long as it doesn't upset my stomach again.",
    cost: "Money's a little tight. I'd want something my insurance covers.",
  },
  topics: {
    adherence: ["miss", "skip", "every day", "as prescribed", "taking them", "side effect", "stomach upset", "adherence", "how often do you take", "remember to take"],
    glucose: ["sugar", "sugars", "glucose", "readings", "check your blood", "numbers", "meter", "finger stick"],
    hypoglycemia: ["low sugar", "lows", "hypoglyc", "shaky", "low blood sugar"],
    foot: ["feet", "foot", "sores", "cuts", "ulcer", "wounds"],
    thirst: ["thirst", "thirsty", "drinking a lot", "polyuria", "polydipsia"],
    cost: ["afford", "cost", "insurance", "pay for"],
  },
  cues: ["living", "concerns", "mood"],
  exam: [
    { key: "vitals", label: "Check vitals", ask: "Let me check your vital signs.", finding: "BP 142/88, HR 76, BMI 33.", match: ["vitals", "vital signs", "blood pressure", "weight"], required: true },
    { key: "feet", label: "Foot exam and monofilament", ask: "I'd like to examine your feet and test the sensation.", finding: "No ulcers or calluses. Decreased monofilament sensation at 4 of 10 sites on both feet. Dorsalis pedis pulses 2+ bilaterally.", match: ["feet", "foot", "monofilament", "sensation", "toes"], required: true },
    { key: "eyes", label: "Look in eyes", ask: "Let me take a look in your eyes.", finding: "Undilated exam limited. No obvious hemorrhages seen.", match: ["eyes", "fundus", "fundoscop", "retina"] },
    { key: "heart", label: "Listen to heart", ask: "I'd like to listen to your heart.", finding: "Regular rate and rhythm. No murmurs.", match: ["heart", "cardiac"] },
  ],
  checklist: [
    { id: "adherence", label: "Metformin adherence and side effects", topics: ["adherence", "meds"], weight: 3, ask: "How are you taking your metformin? Any side effects?" },
    { id: "glucose", label: "Home glucose readings", topics: ["glucose"], weight: 2, ask: "What are your sugars running at home?" },
    { id: "hypo", label: "Low blood sugar episodes", topics: ["hypoglycemia"], weight: 2, redFlag: true, ask: "Any low blood sugars, shaky or sweaty spells?" },
    { id: "diet", label: "Diet and drinks", topics: ["diet", "feeding"], weight: 2, ask: "Tell me about what you eat and drink in a typical day." },
    { id: "exercise", label: "Physical activity", topics: ["exercise_hx"], weight: 1, ask: "How active are you?" },
    { id: "neuro", label: "Numbness or tingling in feet", topics: ["neuro"], weight: 2, ask: "Any numbness or tingling in your feet?" },
    { id: "foot", label: "Foot sores or wounds", topics: ["foot"], weight: 2, redFlag: true, ask: "Any sores or cuts on your feet?" },
    { id: "vision", label: "Vision changes and last eye exam", topics: ["vision"], weight: 2, ask: "Any vision changes? When was your last eye exam?" },
    { id: "polyuria", label: "Thirst and urination", topics: ["thirst", "urinary"], weight: 1, ask: "Have you been extra thirsty or peeing more?" },
    { id: "cv", label: "Chest pain or shortness of breath", topics: ["chest_pain", "sob"], weight: 1, redFlag: true, ask: "Any chest pain or shortness of breath with activity?" },
    { id: "mood", label: "Mood and social support", topics: ["mood", "living"], weight: 1, ask: "How have you been feeling in your mood? Who's at home with you?" },
    { id: "allergies", label: "Allergies", topics: ["allergies"], weight: 1, ask: "Any medicine allergies?" },
    { id: "smoking", label: "Smoking", topics: ["smoking"], weight: 1, ask: "Do you smoke?" },
    { id: "family", label: "Family history", topics: ["family"], weight: 1, ask: "Does diabetes run in your family?" },
  ],
  note: {
    facts: [
      { id: "cc", label: "A1c 8.9%, up from 7.6%", any: ["a1c", "8 9", "hemoglobin a1c"], kind: "pos", weight: 2 },
      { id: "adherence", label: "Skips evening metformin due to GI upset", any: ["skip", "nonadheren", "non adheren", "adherence", "diarrhea", "gi upset", "gi side"], kind: "pos", topic: "adherence", weight: 2 },
      { id: "glucose", label: "Fasting sugars 170 to 190", any: ["170", "190", "fasting", "home glucose", "sugars"], kind: "pos", topic: "glucose", weight: 1 },
      { id: "soda", label: "Three sodas a day", any: ["soda", "sugary drink", "sugar sweetened"], kind: "pos", topic: "diet", weight: 1 },
      { id: "neuropathy", label: "Bilateral foot numbness and tingling", any: ["numb", "tingl", "paresthes", "neuropathy"], kind: "pos", topic: "neuro", weight: 2 },
      { id: "eye", label: "Blurry vision, no eye exam in 2 years", any: ["eye exam", "blurry", "blurred", "ophthalm", "retina"], kind: "pos", topic: "vision", weight: 1 },
      { id: "no_hypo", label: "Denies hypoglycemia", any: ["hypoglyc", "no lows", "denies lows", "lows"], kind: "neg", topic: "hypoglycemia", weight: 1 },
      { id: "no_ulcer", label: "No foot ulcers", any: ["no ulcer", "no sores", "no wounds", "ulcer"], kind: "neg", topic: "foot", weight: 1 },
      { id: "allergy", label: "Sulfa allergy", any: ["sulfa"], kind: "hx", topic: "allergies", weight: 1 },
      { id: "monofilament", label: "Decreased monofilament sensation both feet", any: ["monofilament", "decreased sensation", "reduced sensation"], kind: "exam", exam: "feet", weight: 2 },
    ],
    differential: [
      { dx: "Type 2 diabetes, not at goal", any: ["type 2 diabetes", "t2dm", "dm2", "diabetes", "hyperglycemia", "uncontrolled"], leading: true },
      { dx: "Diabetic peripheral neuropathy", any: ["neuropathy"] },
      { dx: "Medication side effects driving nonadherence", any: ["nonadheren", "non adheren", "side effect", "intoleran", "gi upset"] },
      { dx: "Hypertension, not at goal", any: ["hypertension", "htn", "blood pressure"] },
    ],
    plan: [
      { label: "Switch to metformin extended-release", any: ["extended release", "metformin er", "metformin xr", "xr"], weight: 3 },
      { label: "Add a GLP-1 or SGLT2 medicine", any: ["glp", "semaglutide", "dulaglutide", "liraglutide", "sglt", "empagliflozin", "dapagliflozin", "tirzepatide"], weight: 2 },
      { label: "Eye exam referral", any: ["eye exam", "ophthalm", "retinal", "optometr"], weight: 2 },
      { label: "Urine albumin and kidney labs", any: ["urine albumin", "microalbumin", "uacr", "acr", "egfr", "bmp", "kidney"], weight: 1 },
      { label: "Diet counseling (cut soda)", any: ["diet", "soda", "nutrition", "dietitian", "diabetes education"], weight: 1 },
      { label: "Foot care or podiatry", any: ["podiatr", "foot care", "daily foot", "check her feet"], weight: 1 },
    ],
    contradictions: [{ label: "Wrote she takes metformin as prescribed, but she skips the evening dose", any: ["adherent", "taking as prescribed", "good adherence", "compliant"] }],
  },
  pimp: [
    { q: "What A1c goal would you set for her?", any: ["7", "seven", "under 7", "less than 7"], answer: "Under 7% for most adults, individualized for age and risk of lows." },
    { q: "Which diabetes medicine classes protect the heart and kidneys?", any: ["sglt", "glp", "gliflozin", "glutide"], answer: "SGLT2 inhibitors and GLP-1 receptor agonists." },
    { q: "Name the yearly screening tests for diabetes complications.", any: ["eye", "retin", "urine", "albumin", "foot", "monofilament"], answer: "A dilated eye exam, urine albumin to creatinine ratio with eGFR, and a foot exam with monofilament." },
  ],
  model: "Ms. Brooks is a 61-year-old woman with type 2 diabetes for 8 years and hypertension who is here for follow-up with an A1c of 8.9%, up from 7.6%. She skips her evening metformin most days because of diarrhea, drinks about three sodas a day, and has home fasting sugars of 170 to 190 without any lows. She has several months of bilateral foot numbness and tingling, occasional blurry vision, and no eye exam in 2 years. She lives alone since her husband died last year. She is allergic to sulfa. BP is 142/88, and she has decreased monofilament sensation in both feet without ulcers. Her diabetes is not at goal, mainly from GI intolerance of metformin, and she likely has peripheral neuropathy. I'd switch to metformin extended-release, add a GLP-1 or SGLT2 medicine, refer for an eye exam, check urine albumin and kidney function, and counsel on cutting soda.",
};
