import type { PracticeCase } from "../types";

export const headache: PracticeCase = {
  id: "headache",
  title: "Headache",
  specialty: "Neurology",
  blurb: "A 34-year-old woman with a sudden, severe headache at the gym.",
  patient: {
    name: "Priya Shah",
    age: 34,
    sex: "F",
    affect: "Holding her head, eyes half closed, turned away from the light.",
    opening: "I have the worst headache of my life. It hit me all at once.",
    story: "I was lifting weights, and all of a sudden it felt like I got hit in the back of the head.",
  },
  door: { setting: "Emergency department", vitals: "BP 162/94, HR 88, RR 16, SpO2 99%, T 37.2 C", task: "Take a focused history, do a focused exam, then write a note with your differential and plan." },
  facts: {
    id: "Priya Shah. I'm 34.",
    onset: "About three hours ago. It came on instantly, while I was lifting at the gym. It was at full strength within a minute.",
    thunderclap: "It was instant. Like a thunderclap. It went from nothing to the worst pain in seconds.",
    duration: "It's been there the whole three hours.",
    location: "It's all over, but worst in the back of my head.",
    character: "It's a pounding, exploding kind of pain.",
    radiation: "It goes down into my neck.",
    severity: "Ten out of ten. The worst headache of my life.",
    timing: "It's constant.",
    aggravating: "Light makes it worse, and moving my head.",
    relieving: "Nothing. I took two Tylenol in the car and nothing changed.",
    associated: "I threw up twice, and my neck feels stiff. The lights bother me.",
    prior: "I get migraines a few times a year, but this is completely different. My migraines build up slowly.",
    nausea: "Yes, I've thrown up twice.",
    neck: "Yes, my neck is really stiff. It hurts to bend it forward.",
    photophobia: "Yes, the lights in here are killing me.",
    vision: "No double vision. Just the light bothers me.",
    neuro: "No weakness or numbness, and I can talk fine.",
    confusion: "No, I'm thinking clearly.",
    dizziness: "I didn't pass out. I felt a little dizzy at first.",
    fever: "No fever.",
    trauma: "No, I didn't hit my head.",
    rash: "No rash.",
    pmh: "Just migraines. Otherwise I'm healthy.",
    psh: "No surgeries.",
    meds: "Birth control pills, and sumatriptan when I get a migraine. I didn't take it today.",
    allergies: "No allergies.",
    smoking: "I don't smoke.",
    alcohol: "A glass of wine now and then.",
    drugs: "No drugs.",
    occupation: "I'm an accountant.",
    living: "I live with my husband.",
    family: "My mom had a brain aneurysm. She had surgery for it when she was 50.",
    lmp: "My period was two weeks ago.",
    concerns: "My mom had an aneurysm. I'm scared that's what this is.",
    empathy: "Thank you. It's the worst pain I've ever felt.",
    next: "Okay. Please, anything for the pain.",
  },
  topics: {
    thunderclap: ["sudden", "all at once", "instant", "how quickly", "how fast", "thunderclap", "seconds", "gradual", "build up", "peak"],
    neck: ["stiff neck", "neck stiff", "neck pain", "neck", "bend your head"],
    photophobia: ["light", "bright", "photophobia"],
    confusion: ["confus", "thinking clearly", "memory"],
  },
  cues: ["concerns", "family"],
  exam: [
    { key: "vitals", label: "Check vitals", ask: "Let me check your vital signs.", finding: "BP 162/94, HR 88, RR 16, T 37.2 C, SpO2 99%.", match: ["vitals", "vital signs", "blood pressure", "temperature"], required: true },
    { key: "neuro", label: "Neuro exam", ask: "I'd like to do a neurological exam.", finding: "Alert and oriented. Cranial nerves II to XII intact. Strength 5/5 and sensation intact in all extremities. No pronator drift. Normal finger to nose.", match: ["neuro", "neurological", "strength", "cranial nerves", "reflexes", "sensation"], required: true },
    { key: "neck", label: "Check neck stiffness", ask: "I'm going to check how your neck moves.", finding: "Nuchal rigidity with pain on neck flexion. Positive Brudzinski sign.", match: ["neck", "meningeal", "brudzinski", "kernig", "nuchal"], required: true },
    { key: "eyes", label: "Look in eyes", ask: "I'd like to look in your eyes with a light.", finding: "Pupils equal and reactive. No papilledema. Photophobia on exam.", match: ["eyes", "pupils", "fundus", "fundoscop", "papilledema", "ophthalmoscop"] },
    { key: "skin", label: "Check skin", ask: "Let me check your skin for any rash.", finding: "No rash or petechiae.", match: ["skin", "rash", "petechiae"] },
  ],
  checklist: [
    { id: "onset", label: "Sudden onset, peak within a minute", topics: ["thunderclap", "onset"], weight: 3, redFlag: true, ask: "How quickly did it come on? Was it at full strength right away?" },
    { id: "severity", label: "Worst headache of her life", topics: ["severity"], weight: 2, redFlag: true, ask: "Is this the worst headache you've ever had?" },
    { id: "location", label: "Location", topics: ["location"], weight: 1, ask: "Where is the headache?" },
    { id: "character", label: "Quality", topics: ["character", "open"], weight: 1, ask: "What does it feel like?" },
    { id: "context", label: "What she was doing (exertion)", topics: ["onset", "aggravating"], weight: 1, ask: "What were you doing when it started?" },
    { id: "neck", label: "Neck stiffness", topics: ["neck", "radiation", "associated"], weight: 2, redFlag: true, ask: "Any neck stiffness?" },
    { id: "photophobia", label: "Light sensitivity", topics: ["photophobia", "aggravating", "associated"], weight: 1, ask: "Does light bother you?" },
    { id: "nausea", label: "Nausea and vomiting", topics: ["nausea", "associated"], weight: 1, ask: "Any nausea or vomiting?" },
    { id: "neuro", label: "Weakness, numbness, vision or speech change", topics: ["neuro", "vision", "confusion"], weight: 2, redFlag: true, ask: "Any weakness, numbness, vision changes, or trouble speaking?" },
    { id: "fever", label: "Fever", topics: ["fever"], weight: 1, redFlag: true, ask: "Have you had a fever?" },
    { id: "trauma", label: "Head trauma", topics: ["trauma"], weight: 1, ask: "Did you hit your head?" },
    { id: "prior", label: "Different from prior headaches", topics: ["prior"], weight: 2, ask: "Have you had headaches like this before?" },
    { id: "meds", label: "Medications (OCP, triptan)", topics: ["meds"], weight: 1, ask: "What medicines do you take?" },
    { id: "family", label: "Family history of aneurysm", topics: ["family"], weight: 2, redFlag: true, ask: "Anyone in your family with an aneurysm or bleeding in the brain?" },
    { id: "social", label: "Smoking, alcohol, drugs", topics: ["smoking", "alcohol", "drugs"], weight: 1, ask: "Do you smoke, drink, or use any drugs?" },
  ],
  note: {
    facts: [
      { id: "cc", label: "Sudden severe headache 3 hours ago", any: ["headache", "cephalgia"], kind: "pos", weight: 2 },
      { id: "thunderclap", label: "Thunderclap onset during exertion", any: ["thunderclap", "sudden", "instant", "abrupt", "maximal", "within a minute"], kind: "pos", topic: "thunderclap", weight: 2 },
      { id: "worst", label: "Worst headache of her life", any: ["worst headache", "worst of her life", "10 10", "ten out of ten"], kind: "pos", topic: "severity", weight: 1 },
      { id: "neck", label: "Neck stiffness", any: ["neck stiff", "stiff neck", "nuchal", "meningismus"], kind: "pos", topic: "neck", weight: 2 },
      { id: "vomit", label: "Vomiting twice", any: ["vomit", "emesis"], kind: "pos", topic: "nausea", weight: 1 },
      { id: "photo", label: "Photophobia", any: ["photophobia", "light sensitiv", "light bothers"], kind: "pos", topic: "photophobia", weight: 1 },
      { id: "family", label: "Mother with brain aneurysm", any: ["aneurysm", "mother", "family history"], kind: "hx", topic: "family", weight: 1 },
      { id: "no_focal", label: "Denies weakness, numbness, vision change", any: ["no weakness", "denies weakness", "no focal", "no numbness", "denies numbness", "weakness", "numbness", "focal"], kind: "neg", topic: "neuro", weight: 1 },
      { id: "no_fever", label: "Denies fever", any: ["no fever", "denies fever", "afebrile"], kind: "neg", topic: "fever", weight: 1 },
      { id: "no_trauma", label: "Denies head trauma", any: ["no trauma", "denies trauma", "no head injury", "denies head", "head trauma", "head injury"], kind: "neg", topic: "trauma", weight: 1 },
      { id: "neuro_exam", label: "Non-focal neuro exam", any: ["nonfocal", "non focal", "cranial nerves", "strength 5", "intact"], kind: "exam", exam: "neuro", weight: 1 },
      { id: "neck_exam", label: "Nuchal rigidity on exam", any: ["nuchal rigidity", "brudzinski", "meningismus", "kernig"], kind: "exam", exam: "neck", weight: 1 },
    ],
    differential: [
      { dx: "Subarachnoid hemorrhage", any: ["subarachnoid", "sah", "aneurysmal bleed", "ruptured aneurysm"], leading: true },
      { dx: "Meningitis", any: ["meningitis"] },
      { dx: "Reversible cerebral vasoconstriction syndrome", any: ["rcvs", "vasoconstriction"] },
      { dx: "Cervical artery dissection", any: ["dissection"] },
      { dx: "Migraine", any: ["migraine"] },
    ],
    plan: [
      { label: "Non-contrast head CT", any: ["ct head", "head ct", "non contrast ct", "noncontrast ct", "ct scan", "ct"], weight: 3 },
      { label: "Lumbar puncture if CT is negative", any: ["lumbar puncture", "lp", "xanthochromia", "spinal tap"], weight: 2 },
      { label: "Neurosurgery", any: ["neurosurg"], weight: 1 },
      { label: "Blood pressure control", any: ["blood pressure control", "bp control", "nicardipine", "labetalol", "bp goal"], weight: 1 },
      { label: "Pain and nausea control", any: ["analges", "pain control", "antiemetic", "ondansetron", "zofran"], weight: 1 },
    ],
    contradictions: [{ label: "Called it gradual onset, but it came on instantly", any: ["gradual onset", "came on gradually", "onset was gradual"] }],
  },
  pimp: [
    { q: "What's the first test you'd order?", any: ["ct", "cat scan", "computed tomography"], answer: "A non-contrast head CT, ideally within 6 hours of onset." },
    { q: "If the CT is negative, what next, and what are you looking for?", any: ["lumbar puncture", "lp", "spinal tap", "xanthochromia", "cta", "angiogra"], answer: "A lumbar puncture looking for xanthochromia or red cells that don't clear, or CT angiography." },
    { q: "What's the most common cause of a non-traumatic subarachnoid hemorrhage?", any: ["aneurysm", "berry"], answer: "A ruptured saccular (berry) aneurysm." },
  ],
  model: "Ms. Shah is a 34-year-old woman with a history of migraines who presents 3 hours after the sudden onset of the worst headache of her life, which peaked within a minute while she was lifting weights. It is occipital, radiates to her neck, and is associated with neck stiffness, photophobia, and two episodes of vomiting. It is different from her usual migraines. She denies fever, head trauma, weakness, numbness, or vision changes. Her mother had a brain aneurysm. She is hypertensive to 162/94 with nuchal rigidity and a non-focal neuro exam. My leading concern is subarachnoid hemorrhage. I'd get a non-contrast head CT now, a lumbar puncture if it's negative, control her blood pressure and pain, and involve neurosurgery.",
};
