import type { PracticeCase } from "../types";

export const lowBackPain: PracticeCase = {
  id: "low-back-pain",
  title: "Low back pain",
  specialty: "Primary care",
  blurb: "A 45-year-old warehouse worker who hurt his back moving boxes.",
  patient: {
    name: "James O'Connor",
    age: 45,
    sex: "M",
    affect: "Sitting stiffly, shifting in the chair, frustrated.",
    opening: "My lower back has been killing me since I moved some boxes last week.",
    story: "I was helping my brother move, lifting a bunch of heavy boxes, and the next morning I could barely get out of bed.",
  },
  door: { setting: "Primary care clinic", vitals: "BP 128/82, HR 78, RR 14, T 36.9 C", task: "Take a focused history, do a focused exam, then write a note with your assessment and plan." },
  facts: {
    id: "James O'Connor. I'm 45.",
    onset: "Five days ago. It started the morning after I helped my brother move.",
    duration: "It's been five days. It's a little better than the first day.",
    location: "Low in my back, a little more on the right side.",
    character: "It's a deep ache, and it gets tight, like a spasm.",
    radiation: "It goes into my right buttock sometimes, but not down my leg. Nothing past the knee.",
    severity: "About a six out of ten. It was an eight the first day.",
    timing: "It's there most of the time, worse when I move wrong.",
    aggravating: "Bending over and sitting for a long time make it worse.",
    relieving: "Lying on my back with a pillow under my knees helps. Ibuprofen takes the edge off.",
    associated: "Just the stiffness. Nothing else.",
    prior: "I tweaked it once about ten years ago, but it got better in a week.",
    trauma: "No fall. Just lifting those boxes.",
    cauda: "No, I'm peeing and going to the bathroom normally. No accidents, no trouble getting started.",
    saddle: "No, no numbness down there.",
    neuro: "No weakness in my legs. No numbness or tingling.",
    fever: "No fevers or chills.",
    weight: "No, my weight's been the same.",
    night_pain: "It doesn't wake me up at night unless I roll over wrong.",
    cancer: "No, I've never had cancer.",
    drugs: "No, never used IV drugs or anything like that.",
    steroids: "No, I've never been on steroids.",
    urinary: "Peeing is normal.",
    bowel: "My bowels are normal.",
    pmh: "I have mild high blood pressure. That's it.",
    psh: "No surgeries.",
    meds: "Amlodipine for my blood pressure, and ibuprofen 400 a few times a day this week.",
    allergies: "No allergies.",
    smoking: "I smoke about half a pack a day.",
    alcohol: "A few beers on the weekend.",
    occupation: "I work in a warehouse. I lift and move stock all day.",
    living: "I live with my wife and two kids.",
    family: "My dad had back problems. Nothing serious that I know of.",
    concerns: "I can't afford to miss work. I need to know when I can go back. And do I need an MRI?",
    empathy: "Yeah, thanks. It's been frustrating.",
    next: "Okay. So no MRI?",
  },
  topics: {
    cauda: ["bladder", "bowel", "incontinen", "accidents", "retention", "trouble urinating", "control", "going to the bathroom"],
    saddle: ["saddle", "groin", "numbness down there", "private area", "between your legs", "inner thighs"],
    night_pain: ["at night", "wake you up", "night pain", "rest pain", "while lying"],
    cancer: ["cancer", "tumor", "malignan"],
    steroids: ["steroid", "prednisone"],
  },
  cues: ["concerns"],
  exam: [
    { key: "vitals", label: "Check vitals", ask: "Let me check your vital signs.", finding: "BP 128/82, HR 78, T 36.9 C.", match: ["vitals", "vital signs", "blood pressure", "temperature"] },
    { key: "back", label: "Examine back", ask: "I'd like to look at and press along your back.", finding: "Tender right lumbar paraspinal muscles with spasm. No midline spinal tenderness. Range of motion limited by pain in flexion.", match: ["back", "spine", "lumbar", "paraspinal"], required: true },
    { key: "slr", label: "Straight leg raise", ask: "I'm going to raise each leg while you lie flat.", finding: "Straight leg raise negative on both sides.", match: ["straight leg", "raise your leg", "raise each leg", "leg raise", "slr"], required: true },
    { key: "neuro", label: "Leg strength, reflexes, sensation", ask: "Let me check the strength, reflexes, and feeling in your legs.", finding: "Strength 5/5 in hip flexion, knee extension, ankle dorsiflexion and plantarflexion, and great toe extension. Patellar and Achilles reflexes 2+ and symmetric. Sensation intact.", match: ["strength", "reflexes", "sensation", "neuro", "leg strength", "legs"], required: true },
    { key: "gait", label: "Watch walking", ask: "Can you walk across the room for me, then on your heels and toes?", finding: "Antalgic but steady gait. Able to heel and toe walk.", match: ["walk", "gait", "heels", "toes"] },
  ],
  checklist: [
    { id: "onset", label: "Onset and mechanism", topics: ["onset", "trauma"], weight: 2, ask: "When did it start, and what were you doing?" },
    { id: "location", label: "Location", topics: ["location"], weight: 1, ask: "Where exactly is the pain?" },
    { id: "character", label: "Quality", topics: ["character", "open"], weight: 1, ask: "What does the pain feel like?" },
    { id: "radiation", label: "Radiation down the leg", topics: ["radiation"], weight: 2, ask: "Does it go down your leg?" },
    { id: "severity", label: "Severity", topics: ["severity"], weight: 1, ask: "How bad is it from 0 to 10?" },
    { id: "modifiers", label: "What makes it better or worse", topics: ["aggravating", "relieving"], weight: 1, ask: "What makes it better or worse?" },
    { id: "cauda", label: "Bowel or bladder changes", topics: ["cauda", "urinary", "bowel"], weight: 3, redFlag: true, ask: "Any trouble controlling your bladder or bowels?" },
    { id: "saddle", label: "Saddle numbness", topics: ["saddle"], weight: 2, redFlag: true, ask: "Any numbness in your groin or inner thighs?" },
    { id: "neuro", label: "Leg weakness or numbness", topics: ["neuro"], weight: 2, redFlag: true, ask: "Any weakness or numbness in your legs?" },
    { id: "fever", label: "Fever", topics: ["fever"], weight: 1, redFlag: true, ask: "Any fevers or chills?" },
    { id: "weight", label: "Weight loss or cancer history", topics: ["weight", "cancer"], weight: 2, redFlag: true, ask: "Any unexplained weight loss, or a history of cancer?" },
    { id: "night", label: "Night pain", topics: ["night_pain"], weight: 1, redFlag: true, ask: "Does the pain wake you at night?" },
    { id: "ivdu", label: "IV drug use or steroids", topics: ["drugs", "steroids"], weight: 1, redFlag: true, ask: "Any IV drug use or long-term steroid use?" },
    { id: "meds", label: "What he's tried", topics: ["meds", "relieving"], weight: 1, ask: "What have you taken for it?" },
    { id: "work", label: "Occupation and work demands", topics: ["occupation"], weight: 1, ask: "What kind of work do you do?" },
  ],
  note: {
    facts: [
      { id: "cc", label: "Low back pain for 5 days after lifting", any: ["low back pain", "lbp", "lumbar", "back pain"], kind: "pos", weight: 2 },
      { id: "mechanism", label: "Lifting heavy boxes", any: ["lifting", "boxes", "lift"], kind: "pos", topic: "onset", weight: 1 },
      { id: "radiation", label: "Radiates to right buttock, not below knee", any: ["buttock", "not below the knee", "no radiation below", "does not radiate"], kind: "pos", topic: "radiation", weight: 2 },
      { id: "no_cauda", label: "No bowel or bladder dysfunction", any: ["bowel", "bladder", "incontinen", "retention"], kind: "neg", topic: "cauda", weight: 3 },
      { id: "no_saddle", label: "No saddle anesthesia", any: ["saddle"], kind: "neg", topic: "saddle", weight: 2 },
      { id: "no_weak", label: "No leg weakness or numbness", any: ["no weakness", "denies weakness", "no numbness", "denies numbness", "leg weakness"], kind: "neg", topic: "neuro", weight: 1 },
      { id: "no_fever", label: "No fever", any: ["no fever", "denies fever", "afebrile", "fever"], kind: "neg", topic: "fever", weight: 1 },
      { id: "no_cancer", label: "No cancer history or weight loss", any: ["no history of cancer", "no cancer", "weight loss", "no weight"], kind: "neg", topic: "cancer", weight: 1 },
      { id: "paraspinal", label: "Right paraspinal tenderness, no midline tenderness", any: ["paraspinal", "no midline", "spasm"], kind: "exam", exam: "back", weight: 1 },
      { id: "slr", label: "Negative straight leg raise", any: ["straight leg", "slr"], kind: "exam", exam: "slr", weight: 2 },
      { id: "neuro_exam", label: "Normal strength, reflexes, sensation", any: ["5 5", "strength", "reflexes", "sensation intact"], kind: "exam", exam: "neuro", weight: 1 },
    ],
    differential: [
      { dx: "Acute mechanical low back strain", any: ["strain", "mechanical", "musculoskeletal", "sprain", "muscle spasm"], leading: true },
      { dx: "Lumbar radiculopathy or disc herniation", any: ["radiculopathy", "herniat", "disc", "sciatica"] },
      { dx: "Cauda equina syndrome (ruled out by history)", any: ["cauda equina"] },
      { dx: "Spinal infection or epidural abscess", any: ["abscess", "osteomyelitis", "discitis", "infection"] },
      { dx: "Malignancy", any: ["malignan", "metasta", "cancer"] },
    ],
    plan: [
      { label: "NSAIDs", any: ["nsaid", "ibuprofen", "naproxen"], weight: 2 },
      { label: "Stay active, no bed rest", any: ["stay active", "activity as tolerated", "avoid bed rest", "no bed rest", "remain active"], weight: 2 },
      { label: "No imaging now", any: ["no imaging", "imaging not", "no mri", "mri not", "no x ray", "not indicated"], weight: 3 },
      { label: "Heat or physical therapy", any: ["heat", "physical therapy", "pt"], weight: 1 },
      { label: "Return precautions for red flags", any: ["return", "precaution", "red flag"], weight: 2 },
      { label: "Work note or modified duty", any: ["work note", "modified duty", "light duty", "restrictions", "lifting restriction"], weight: 1 },
    ],
    contradictions: [{ label: "Wrote pain radiates below the knee, which he denied", any: ["below the knee", "down the leg", "sciatica"] }],
  },
  pimp: [
    { q: "When would you get imaging for acute low back pain?", any: ["red flag", "6 weeks", "six weeks", "neurolog", "cauda", "cancer", "fever"], answer: "Only with red flags such as neurologic deficits, suspected cauda equina, infection, or cancer, or if pain lasts beyond about 6 weeks despite treatment." },
    { q: "What are the classic signs of cauda equina syndrome?", any: ["saddle", "retention", "incontinen", "bladder", "bowel"], answer: "Saddle anesthesia, urinary retention or incontinence, bowel dysfunction, and bilateral leg weakness or sciatica." },
    { q: "What makes a straight leg raise positive?", any: ["below the knee", "radiat", "30", "70", "leg pain", "sciatic"], answer: "Reproducing radiating leg pain below the knee between about 30 and 70 degrees of elevation." },
  ],
  model: "Mr. O'Connor is a 45-year-old warehouse worker with hypertension who presents with 5 days of right-sided low back pain that started the morning after lifting heavy boxes. It is an aching, spasm-like pain that radiates to the right buttock but not below the knee, worse with bending and sitting, and better with rest and ibuprofen. He denies bowel or bladder changes, saddle numbness, leg weakness, fever, weight loss, night pain, cancer history, IV drug use, and steroid use. On exam he has right lumbar paraspinal tenderness and spasm without midline tenderness, a negative straight leg raise, and a normal neurologic exam. This is an acute mechanical low back strain with no red flags. I'd recommend NSAIDs, heat, staying active, no imaging right now, a note for modified duty, and return precautions for red flags, with physical therapy if not better in a few weeks.",
};
