import type { PracticeCase } from "../types";

export const pediatricFever: PracticeCase = {
  id: "pediatric-fever",
  title: "Fever in a toddler",
  specialty: "Pediatrics",
  blurb: "A mom brings in her 18-month-old with 3 days of fever. You talk to the parent.",
  patient: {
    name: "Mateo Martinez",
    age: 1,
    sex: "M",
    affect: "Mom looks tired. Mateo is fussy on her lap but calms when she rocks him.",
    opening: "Mateo's had a fever for three days, and he keeps pulling at his ear.",
    story: "He just hasn't been himself. The fever goes up at night, and he's been cranky.",
    speaker: { name: "Ana Martinez", relation: "mother" },
  },
  door: { setting: "Pediatric clinic, same-day visit", vitals: "T 39.2 C, HR 150, RR 30, SpO2 99%, weight 11 kg. Age 18 months.", task: "Take a history from the parent, do a focused exam, then write a note with your assessment and plan." },
  facts: {
    id: "This is Mateo. He's 18 months old. I'm his mom, Ana.",
    onset: "The fever started three days ago.",
    duration: "Three days now. It goes up and down.",
    fever: "It's been up to 103.5 at home, by the forehead thermometer. It comes down with Tylenol.",
    location: "He keeps pulling at his right ear.",
    ear: "Yes, he tugs at his right ear all the time, and he cries when he lies down.",
    severity: "The highest was 103.5.",
    timing: "It's worse at night.",
    relieving: "Tylenol or Motrin brings it down for a few hours.",
    associated: "He's had a runny nose, and he's cranky and pulling at his ear.",
    cough: "A little cough with the runny nose. Not much.",
    sob: "No, he's breathing fine.",
    feeding: "He's not eating much food, but he's drinking his milk and water okay.",
    diapers: "Maybe four wet diapers today. A little less than usual.",
    nausea: "No throwing up.",
    bowel: "No diarrhea.",
    rash: "No rash.",
    neck: "No, he moves his neck fine. He looks all around.",
    behavior: "He's cranky, but when the fever comes down he plays and laughs like normal.",
    seizure: "No, no shaking or seizures.",
    contacts: "He goes to daycare, and a few kids there have colds.",
    immunizations: "He's up to date on all his shots.",
    birth: "He was born on time, no problems.",
    pmh: "He's been healthy. He had one ear infection when he was a baby.",
    prior: "One ear infection when he was about 9 months old.",
    recent_antibiotics: "No antibiotics in the last few months.",
    meds: "Just Tylenol and Motrin for the fever.",
    dosing: "I give him about 5 milliliters of Tylenol, every four hours or so.",
    allergies: "No allergies that we know of.",
    family: "Nothing special. I had a lot of ear infections as a kid.",
    living: "He lives with me, his dad, and his big sister.",
    smoking: "His dad smokes, but outside.",
    concerns: "I'm worried it could be something serious, like meningitis. My friend's baby had that.",
    empathy: "Thank you. I haven't slept much.",
    next: "Okay. Does he need antibiotics?",
  },
  topics: {
    ear: ["ear", "ears", "tugging", "pulling"],
    neck: ["stiff neck", "neck"],
    seizure: ["seizure", "shaking", "convuls", "jerking"],
    recent_antibiotics: ["antibiotic", "antibiotics", "amoxicillin"],
    dosing: ["how much tylenol", "how much motrin", "dose", "dosing", "how much do you give", "how often do you give"],
  },
  cues: ["concerns"],
  exam: [
    { key: "vitals", label: "Check vitals", ask: "Let me check his vital signs.", finding: "T 39.2 C, HR 150, RR 30, SpO2 99%, weight 11 kg.", match: ["vitals", "vital signs", "temperature", "heart rate", "weight"], required: true },
    { key: "ears", label: "Look in ears", ask: "I'd like to look in his ears.", finding: "Right tympanic membrane bulging, red, and not moving. Left tympanic membrane normal.", match: ["ears", "ear", "otoscope", "tympanic", "eardrum"], required: true },
    { key: "throat", label: "Look in throat", ask: "Let me look in his mouth and throat.", finding: "Mild clear nasal discharge. Throat mildly red, no exudate. Moist mucous membranes.", match: ["throat", "mouth", "pharynx", "nose"] },
    { key: "lungs", label: "Listen to lungs", ask: "I'd like to listen to his lungs.", finding: "Clear bilaterally. No retractions or wheezing.", match: ["lungs", "lung", "breathing", "chest"], required: true },
    { key: "neck", label: "Check neck", ask: "Let me check his neck.", finding: "Supple, full range of motion. Small mobile anterior cervical nodes.", match: ["neck", "meningeal", "nuchal"] },
    { key: "skin", label: "Check skin", ask: "Let me look at his skin.", finding: "No rash or petechiae. Capillary refill under 2 seconds.", match: ["skin", "rash", "capillary refill", "hydration"] },
  ],
  checklist: [
    { id: "fever", label: "Fever height and duration", topics: ["fever", "onset", "duration", "severity"], weight: 2, ask: "How high has the fever been, and for how long?" },
    { id: "ear", label: "Ear pulling or pain", topics: ["ear", "location", "associated"], weight: 2, ask: "Has he been pulling at his ears?" },
    { id: "uri", label: "Runny nose or cough", topics: ["cough", "associated"], weight: 1, ask: "Any runny nose or cough?" },
    { id: "feeding", label: "Eating and drinking", topics: ["feeding"], weight: 2, ask: "Is he eating and drinking?" },
    { id: "diapers", label: "Wet diapers", topics: ["diapers"], weight: 2, redFlag: true, ask: "How many wet diapers today?" },
    { id: "gi", label: "Vomiting or diarrhea", topics: ["nausea", "bowel"], weight: 1, ask: "Any vomiting or diarrhea?" },
    { id: "rash", label: "Rash", topics: ["rash"], weight: 1, redFlag: true, ask: "Any rash?" },
    { id: "behavior", label: "Activity and alertness", topics: ["behavior"], weight: 2, redFlag: true, ask: "Is he playful when the fever is down, or very sleepy?" },
    { id: "neck", label: "Stiff neck or seizures", topics: ["neck", "seizure"], weight: 1, redFlag: true, ask: "Any stiff neck or seizures?" },
    { id: "sob", label: "Breathing trouble", topics: ["sob"], weight: 1, ask: "Any trouble breathing?" },
    { id: "vaccines", label: "Immunizations", topics: ["immunizations"], weight: 2, ask: "Is he up to date on his shots?" },
    { id: "contacts", label: "Daycare and sick contacts", topics: ["contacts"], weight: 1, ask: "Does he go to daycare? Anyone sick?" },
    { id: "abx", label: "Recent antibiotics", topics: ["recent_antibiotics"], weight: 1, ask: "Has he had antibiotics recently?" },
    { id: "meds", label: "Fever medicines and doses", topics: ["meds", "relieving", "dosing"], weight: 1, ask: "What have you given him for the fever, and how much?" },
    { id: "allergies", label: "Allergies", topics: ["allergies"], weight: 1, ask: "Any allergies to medicines?" },
  ],
  note: {
    facts: [
      { id: "cc", label: "Fever to 103.5 F for 3 days", any: ["fever", "103", "febrile"], kind: "pos", topic: "fever", weight: 2 },
      { id: "ear", label: "Pulling at right ear", any: ["ear pulling", "pulling at", "tugging", "otalgia", "right ear"], kind: "pos", topic: "ear", weight: 2 },
      { id: "uri", label: "Runny nose, daycare contacts", any: ["rhinorrhea", "runny nose", "daycare", "uri"], kind: "pos", topic: "contacts", weight: 1 },
      { id: "hydration", label: "Drinking well, 4 wet diapers", any: ["wet diaper", "drinking", "tolerating", "po intake", "hydrat"], kind: "pos", topic: "diapers", weight: 2 },
      { id: "playful", label: "Playful when afebrile", any: ["playful", "consolable", "active", "interactive", "well appearing"], kind: "pos", topic: "behavior", weight: 1 },
      { id: "vaccines", label: "Immunizations up to date", any: ["immunizations", "vaccin", "utd", "up to date"], kind: "hx", topic: "immunizations", weight: 1 },
      { id: "no_rash", label: "No rash", any: ["no rash", "denies rash"], kind: "neg", topic: "rash", weight: 1 },
      { id: "no_vomit", label: "No vomiting or diarrhea", any: ["no vomiting", "no diarrhea", "denies vomiting", "no v d"], kind: "neg", topic: "nausea", weight: 1 },
      { id: "tm", label: "Right TM bulging and red", any: ["bulging", "tympanic membrane", "tm", "erythematous"], kind: "exam", exam: "ears", weight: 3 },
      { id: "lungs", label: "Lungs clear", any: ["lungs clear", "clear bilaterally", "cta", "no wheez"], kind: "exam", exam: "lungs", weight: 1 },
      { id: "neck", label: "Neck supple", any: ["supple", "no meningismus", "no nuchal"], kind: "exam", exam: "neck", weight: 1 },
    ],
    differential: [
      { dx: "Acute otitis media, right", any: ["otitis media", "aom", "ear infection"], leading: true },
      { dx: "Viral upper respiratory infection", any: ["viral", "uri", "upper respiratory"] },
      { dx: "Urinary tract infection", any: ["uti", "urinary tract"] },
      { dx: "Pneumonia", any: ["pneumonia"] },
      { dx: "Meningitis (unlikely)", any: ["meningitis"] },
    ],
    plan: [
      { label: "High-dose amoxicillin", any: ["amoxicillin", "amox"], weight: 3 },
      { label: "Weight-based dose (80 to 90 mg/kg/day)", any: ["80", "90", "mg kg"], weight: 2 },
      { label: "Fever and pain control dosed by weight", any: ["acetaminophen", "tylenol", "ibuprofen", "motrin", "antipyretic"], weight: 1 },
      { label: "Return precautions", any: ["return", "precaution", "lethargic", "wet diapers", "stiff neck", "worse"], weight: 2 },
      { label: "Recheck if not better in 48 to 72 hours", any: ["48", "72", "follow up", "recheck", "2 to 3 days"], weight: 1 },
    ],
    contradictions: [{ label: "Wrote vomiting, which mom denied", any: ["vomiting x", "has been vomiting", "with vomiting", "emesis"] }],
  },
  pimp: [
    { q: "What antibiotic and dose would you start?", any: ["amoxicillin", "amox"], answer: "High-dose amoxicillin, 80 to 90 mg per kg per day divided twice daily, for 10 days at this age." },
    { q: "What signs would tell you he's getting dehydrated?", any: ["diaper", "tears", "dry mouth", "mucous", "sunken", "capillary", "letharg", "urine"], answer: "Fewer wet diapers, no tears, dry mouth, sunken eyes or fontanelle, slow capillary refill, or lethargy." },
    { q: "Why does being up to date on vaccines matter for a febrile toddler?", any: ["pneumococc", "hib", "haemophilus", "bacteremia", "meningitis", "invasive"], answer: "Pneumococcal and Hib vaccines make serious bacterial infections like bacteremia and meningitis much less likely." },
  ],
  model: "Mateo is an 18-month-old boy with up-to-date immunizations, brought in by his mother with 3 days of fever to 103.5 F, right ear pulling, and runny nose, with sick contacts at daycare. He is drinking well with 4 wet diapers today and is playful when the fever is down. No vomiting, diarrhea, rash, stiff neck, or seizures. He's had no recent antibiotics and has no allergies. On exam he is febrile to 39.2 with a bulging, red, immobile right tympanic membrane, clear lungs, a supple neck, and no rash. This is acute otitis media on the right. I'd start high-dose amoxicillin at 90 mg per kg per day for 10 days, dose Tylenol or Motrin by weight, and give return precautions for lethargy, fewer wet diapers, stiff neck, or rash, with a recheck if he's not better in 48 to 72 hours.",
};
