import type { PracticeCase } from "../types";

export const shortnessOfBreath: PracticeCase = {
  id: "shortness-of-breath",
  title: "Shortness of breath",
  specialty: "Internal medicine",
  blurb: "A 72-year-old woman who can't catch her breath lying down.",
  patient: {
    name: "Dorothy Nguyen",
    age: 72,
    sex: "F",
    affect: "Sitting upright, speaking in short sentences, a little winded.",
    opening: "I can't catch my breath. It's been getting worse all week.",
    story: "At first it was just on the stairs. Now I get winded walking to the kitchen.",
  },
  door: { setting: "Emergency department", vitals: "BP 168/96, HR 98, RR 24, SpO2 91% on room air, T 36.8 C", task: "Take a focused history, do a focused exam, then write a note with your differential and plan." },
  facts: {
    id: "Dorothy Nguyen. I'm 72.",
    onset: "It started about a week ago and has gotten worse every day.",
    duration: "A week now.",
    character: "I just can't get enough air.",
    sob: "Yes. I get winded just walking to the kitchen, and it's worse when I lie down.",
    severity: "Walking to the kitchen wears me out now.",
    timing: "It's there all the time, but worse when I move or lie down.",
    aggravating: "Walking, and lying flat. I have to sleep sitting up.",
    orthopnea: "I've been sleeping on three pillows. If I lie flat, I can't breathe.",
    pnd: "Yes, twice this week I woke up gasping and had to sit on the edge of the bed.",
    relieving: "Sitting up helps a little.",
    associated: "My ankles are swollen, and I've gained some weight. I have a little cough at night.",
    swelling: "Both ankles are puffy. My shoes are tight.",
    weight: "About six pounds this week, on my bathroom scale.",
    cough: "A dry cough, mostly at night. Nothing coming up.",
    chest_pain: "No chest pain.",
    palpitations: "No racing heart.",
    fever: "No fever or chills.",
    dizziness: "No, I haven't fainted.",
    clot: "No, I haven't been on a long trip, and my calves don't hurt.",
    prior: "Something like this happened two years ago, and they said it was my heart. I got a water pill.",
    pmh: "High blood pressure, and I had a heart attack in 2019. They said my heart is a bit weak.",
    psh: "They put a stent in my heart in 2019.",
    meds: "Metoprolol, lisinopril, atorvastatin, and aspirin. I was on furosemide, but I ran out two weeks ago.",
    adherence: "I ran out of the water pill two weeks ago and didn't get it refilled. The pharmacy was closed and then I forgot.",
    diet: "I've been eating a lot of canned soup. It's easy.",
    allergies: "No allergies.",
    smoking: "I quit smoking 20 years ago.",
    alcohol: "No, I don't drink.",
    drugs: "No.",
    occupation: "I'm a retired teacher.",
    living: "I live with my husband.",
    family: "My sister has heart failure.",
    concerns: "I'm scared I'll have to stay in the hospital. My husband needs me at home.",
    empathy: "Thank you, dear.",
    next: "Okay. Will I have to stay overnight?",
  },
  topics: {
    orthopnea: ["lie flat", "lying flat", "lay flat", "pillows", "lying down", "sleep sitting", "orthopnea", "recliner"],
    pnd: ["wake up", "waking up", "woke up", "gasping", "at night short", "middle of the night", "pnd"],
    adherence: ["missed", "miss", "run out", "ran out", "taking them", "every day", "as prescribed", "refill"],
    clot: ["long trip", "travel", "calf", "calves", "blood clot", "recent surgery", "immobil"],
  },
  cues: ["concerns"],
  exam: [
    { key: "vitals", label: "Check vitals", ask: "Let me check your vital signs.", finding: "BP 168/96, HR 98, RR 24, SpO2 91% on room air.", match: ["vitals", "vital signs", "oxygen", "blood pressure"], required: true },
    { key: "lungs", label: "Listen to lungs", ask: "I'd like to listen to your lungs.", finding: "Crackles in both lung bases, a third of the way up. No wheezing.", match: ["lungs", "lung", "breathing", "back"], required: true },
    { key: "heart", label: "Listen to heart", ask: "I'd like to listen to your heart.", finding: "Regular rhythm. S3 gallop. No murmur.", match: ["heart", "cardiac"], required: true },
    { key: "neck", label: "Look at neck veins", ask: "Let me look at the veins in your neck.", finding: "Jugular venous pressure elevated to 12 cm. Positive hepatojugular reflux.", match: ["neck", "jvp", "jugular", "neck veins"], required: true },
    { key: "legs", label: "Check legs", ask: "Let me press on your ankles and shins.", finding: "2+ pitting edema to the mid shin, both legs. Calves soft and not tender.", match: ["legs", "ankles", "edema", "shins", "calves", "swelling"], required: true },
  ],
  checklist: [
    { id: "onset", label: "Onset and progression", topics: ["onset", "duration"], weight: 1, ask: "When did this start, and is it getting worse?" },
    { id: "exertion", label: "Exercise tolerance", topics: ["severity", "aggravating"], weight: 1, ask: "How far can you walk before you get short of breath?" },
    { id: "orthopnea", label: "Orthopnea (pillows)", topics: ["orthopnea"], weight: 2, ask: "Can you lie flat? How many pillows do you sleep on?" },
    { id: "pnd", label: "Waking up gasping at night", topics: ["pnd"], weight: 2, ask: "Do you wake up at night short of breath?" },
    { id: "edema", label: "Leg swelling", topics: ["swelling", "associated"], weight: 2, ask: "Any swelling in your legs?" },
    { id: "weight", label: "Weight gain", topics: ["weight"], weight: 1, ask: "Any change in your weight?" },
    { id: "chest_pain", label: "Chest pain", topics: ["chest_pain"], weight: 2, redFlag: true, ask: "Any chest pain or pressure?" },
    { id: "cough", label: "Cough or fever", topics: ["cough", "fever"], weight: 1, ask: "Any cough or fever?" },
    { id: "syncope", label: "Fainting or palpitations", topics: ["dizziness", "palpitations"], weight: 1, redFlag: true, ask: "Any fainting or racing heart?" },
    { id: "clot", label: "Clot risk", topics: ["clot"], weight: 1, ask: "Any recent travel, surgery, or calf pain?" },
    { id: "pmh", label: "Heart history", topics: ["pmh", "psh", "prior"], weight: 2, ask: "Have you had any heart problems before?" },
    { id: "meds", label: "Medications", topics: ["meds"], weight: 1, ask: "What medicines do you take?" },
    { id: "adherence", label: "Ran out of diuretic", topics: ["adherence", "meds"], weight: 3, redFlag: true, ask: "Have you missed any doses or run out of anything?" },
    { id: "diet", label: "Salt in diet", topics: ["diet"], weight: 1, ask: "Have you been eating anything salty?" },
    { id: "smoking", label: "Smoking history", topics: ["smoking"], weight: 1, ask: "Do you or did you smoke?" },
  ],
  note: {
    facts: [
      { id: "cc", label: "Worsening shortness of breath for 1 week", any: ["dyspnea", "shortness of breath", "sob", "short of breath"], kind: "pos", weight: 2 },
      { id: "orthopnea", label: "Three-pillow orthopnea", any: ["orthopnea", "pillow"], kind: "pos", topic: "orthopnea", weight: 2 },
      { id: "pnd", label: "Paroxysmal nocturnal dyspnea", any: ["pnd", "paroxysmal", "wakes up gasping", "nocturnal"], kind: "pos", topic: "pnd", weight: 1 },
      { id: "edema", label: "Bilateral ankle swelling", any: ["edema", "swelling", "swollen"], kind: "pos", topic: "swelling", weight: 1 },
      { id: "weight", label: "6 lb weight gain", any: ["weight gain", "6 lb", "6 pound", "six pound"], kind: "pos", topic: "weight", weight: 1 },
      { id: "adherence", label: "Ran out of furosemide 2 weeks ago", any: ["ran out", "furosemide", "lasix", "diuretic", "nonadheren"], kind: "pos", topic: "adherence", weight: 3 },
      { id: "salt", label: "High-salt canned soup", any: ["salt", "sodium", "soup"], kind: "pos", topic: "diet", weight: 1 },
      { id: "history", label: "Prior MI with stent and weak heart", any: ["mi", "myocardial infarction", "stent", "cad", "heart attack", "hfref", "heart failure"], kind: "hx", topic: "pmh", weight: 1 },
      { id: "no_cp", label: "Denies chest pain", any: ["no chest pain", "denies chest pain"], kind: "neg", topic: "chest_pain", weight: 1 },
      { id: "crackles", label: "Bibasilar crackles", any: ["crackles", "rales", "bibasilar"], kind: "exam", exam: "lungs", weight: 1 },
      { id: "jvd", label: "Elevated JVP", any: ["jvd", "jvp", "jugular"], kind: "exam", exam: "neck", weight: 1 },
      { id: "s3", label: "S3 gallop", any: ["s3", "gallop"], kind: "exam", exam: "heart", weight: 1 },
      { id: "pitting", label: "2+ pitting edema", any: ["pitting"], kind: "exam", exam: "legs", weight: 1 },
    ],
    differential: [
      { dx: "Acute decompensated heart failure", any: ["heart failure", "chf", "hf", "adhf", "decompensat", "volume overload"], leading: true },
      { dx: "Acute coronary syndrome", any: ["acs", "acute coronary", "ischemia", "nstemi"] },
      { dx: "Pneumonia", any: ["pneumonia"] },
      { dx: "Pulmonary embolism", any: ["pulmonary embol", "pe"] },
      { dx: "COPD exacerbation", any: ["copd"] },
    ],
    plan: [
      { label: "IV furosemide", any: ["iv furosemide", "iv lasix", "diures", "furosemide", "lasix"], weight: 3 },
      { label: "BNP", any: ["bnp", "natriuretic"], weight: 2 },
      { label: "Chest X-ray", any: ["chest x ray", "chest xray", "cxr"], weight: 1 },
      { label: "ECG and troponin", any: ["ecg", "ekg", "troponin"], weight: 2 },
      { label: "Oxygen", any: ["oxygen", "o2", "supplemental"], weight: 1 },
      { label: "Echocardiogram", any: ["echo", "tte"], weight: 1 },
      { label: "Daily weights, low salt, refill diuretic", any: ["daily weight", "low salt", "sodium restriction", "refill", "fluid restriction"], weight: 1 },
    ],
    contradictions: [{ label: "Wrote she takes all her medicines, but she ran out of furosemide", any: ["adherent", "compliant", "taking all"] }],
  },
  pimp: [
    { q: "Which lab helps confirm heart failure here?", any: ["bnp", "natriuretic"], answer: "BNP or NT-proBNP." },
    { q: "What does orthopnea mean, and why does it happen?", any: ["lying flat", "lie flat", "lying down", "venous return", "redistribut", "supine"], answer: "Shortness of breath when lying flat, because more blood returns to the heart and backs up into the lungs." },
    { q: "Name drugs that lower mortality in heart failure with reduced ejection fraction.", any: ["beta blocker", "metoprolol", "carvedilol", "ace", "arb", "arni", "sacubitril", "spironolactone", "mra", "sglt"], answer: "Beta blockers, ARNI or ACE inhibitor or ARB, mineralocorticoid antagonists, and SGLT2 inhibitors." },
  ],
  model: "Mrs. Nguyen is a 72-year-old woman with hypertension and a prior MI with stent in 2019 who presents with a week of worsening shortness of breath, three-pillow orthopnea, paroxysmal nocturnal dyspnea, bilateral ankle swelling, and a 6 lb weight gain after running out of furosemide 2 weeks ago and eating salty canned soup. She denies chest pain, fever, and fainting. She is hypertensive, tachypneic, and saturating 91% on room air, with bibasilar crackles, an S3, elevated JVP, and 2+ pitting edema. This is most likely acute decompensated heart failure from diuretic nonadherence and a salt load. I'd give oxygen and IV furosemide, check BNP, troponin, ECG, and a chest X-ray, get an echo, and plan daily weights, a low-salt diet, and a reliable diuretic refill.",
};
