export interface EvidenceEntry {
  id: string;
  title: string;
  org: string;
  year: number;
  url: string;
  keywords: string[];
  text: string;
}

export const EVIDENCE: EvidenceEntry[] = [
  { id: "uspstf-crc", title: "Colorectal cancer screening", org: "USPSTF", year: 2021, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/colorectal-cancer-screening", keywords: ["colorectal", "colon", "colonoscopy", "fit", "stool", "cologuard", "screening"], text: "Screen adults 50 to 75 (grade A) and 45 to 49 (grade B) for colorectal cancer; screening 76 to 85 is selective (grade C). Options: annual FIT or high-sensitivity gFOBT, stool DNA-FIT every 1 to 3 years, CT colonography every 5 years, flexible sigmoidoscopy every 5 years (or every 10 years with annual FIT), or colonoscopy every 10 years." },
  { id: "uspstf-breast", title: "Breast cancer screening", org: "USPSTF", year: 2024, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/breast-cancer-screening", keywords: ["breast", "mammogram", "mammography", "screening"], text: "Biennial screening mammography for women 40 to 74 (grade B). Evidence is insufficient for women 75 and older and for supplemental ultrasound or MRI in dense breasts." },
  { id: "uspstf-cervical", title: "Cervical cancer screening", org: "USPSTF", year: 2018, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/cervical-cancer-screening", keywords: ["cervical", "pap", "hpv", "cytology", "screening"], text: "Ages 21 to 29: cervical cytology every 3 years. Ages 30 to 65: cytology every 3 years, high-risk HPV testing alone every 5 years, or cotesting every 5 years (grade A). Do not screen under 21, after 65 with adequate prior screening, or after hysterectomy with cervix removed for benign disease." },
  { id: "uspstf-lung", title: "Lung cancer screening", org: "USPSTF", year: 2021, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/lung-cancer-screening", keywords: ["lung", "ldct", "ct", "smoker", "pack-year", "screening"], text: "Annual low-dose CT for adults 50 to 80 with a 20 pack-year smoking history who currently smoke or quit within the past 15 years (grade B). Stop once 15 years have passed since quitting or if health limits life expectancy or willingness to have curative surgery." },
  { id: "uspstf-aaa", title: "Abdominal aortic aneurysm screening", org: "USPSTF", year: 2019, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/abdominal-aortic-aneurysm-screening", keywords: ["aaa", "aortic", "aneurysm", "ultrasound", "screening"], text: "One-time ultrasound screening for men 65 to 75 who have ever smoked (grade B); selective for men 65 to 75 who never smoked (grade C)." },
  { id: "uspstf-diabetes", title: "Prediabetes and type 2 diabetes screening", org: "USPSTF", year: 2021, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/screening-for-prediabetes-and-type-2-diabetes", keywords: ["diabetes", "prediabetes", "a1c", "glucose", "screening", "overweight"], text: "Screen adults 35 to 70 with overweight or obesity for prediabetes and type 2 diabetes (grade B), and refer those with prediabetes to preventive interventions." },
  { id: "uspstf-htn", title: "Hypertension screening in adults", org: "USPSTF", year: 2021, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/hypertension-in-adults-screening", keywords: ["hypertension", "blood pressure", "screening", "home", "ambulatory"], text: "Screen adults 18 and older with office blood pressure measurement and confirm the diagnosis with measurements outside the clinical setting before starting treatment (grade A). Screen yearly from age 40 or with risk factors; every 3 to 5 years for adults 18 to 39 at low risk with normal readings." },
  { id: "uspstf-statin", title: "Statin use for primary prevention of cardiovascular disease", org: "USPSTF", year: 2022, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/statin-use-in-adults-preventive-medication", keywords: ["statin", "cholesterol", "primary prevention", "cardiovascular", "ascvd"], text: "Prescribe a statin for adults 40 to 75 with at least one CVD risk factor (dyslipidemia, diabetes, hypertension, or smoking) and a 10-year CVD risk of 10% or more (grade B). Offer selectively when risk is 7.5% to under 10% (grade C)." },
  { id: "uspstf-depression", title: "Depression and anxiety screening in adults", org: "USPSTF", year: 2023, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/screening-depression-suicide-risk-adults", keywords: ["depression", "anxiety", "phq", "gad", "screening", "postpartum"], text: "Screen all adults for depression, including pregnant and postpartum people (grade B). Screen adults 64 and younger for anxiety disorders (grade B). Evidence is insufficient for routine suicide-risk screening in adults without symptoms." },
  { id: "uspstf-osteo", title: "Osteoporosis screening", org: "USPSTF", year: 2025, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/osteoporosis-screening", keywords: ["osteoporosis", "dexa", "bone density", "fracture", "screening"], text: "Screen women 65 and older, and postmenopausal women younger than 65 at increased risk, for osteoporosis to prevent fractures (grade B). Evidence is insufficient for men." },
  { id: "uspstf-hcv", title: "Hepatitis C screening", org: "USPSTF", year: 2020, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/hepatitis-c-screening", keywords: ["hepatitis c", "hcv", "screening"], text: "Screen all adults 18 to 79 for hepatitis C virus infection at least once (grade B); repeat for people with ongoing risk such as injection drug use." },
  { id: "uspstf-hiv", title: "HIV screening", org: "USPSTF", year: 2019, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/human-immunodeficiency-virus-hiv-infection-screening", keywords: ["hiv", "screening"], text: "Screen adolescents and adults 15 to 65 for HIV, younger and older people at increased risk, and all pregnant people (grade A)." },
  { id: "uspstf-alcohol", title: "Unhealthy alcohol use", org: "USPSTF", year: 2018, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/unhealthy-alcohol-use-in-adolescents-and-adults-screening-and-behavioral-counseling-interventions", keywords: ["alcohol", "audit-c", "drinking", "screening", "counseling"], text: "Screen adults 18 and older for unhealthy alcohol use in primary care (for example, AUDIT-C or a single-question screen) and provide brief behavioral counseling to those who drink riskily (grade B)." },
  { id: "uspstf-tobacco", title: "Tobacco cessation in adults", org: "USPSTF", year: 2021, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/tobacco-use-in-adults-and-pregnant-women-counseling-and-interventions", keywords: ["tobacco", "smoking", "cessation", "quit", "varenicline", "nicotine", "bupropion"], text: "Ask all adults about tobacco use, advise them to stop, and provide behavioral interventions and FDA-approved pharmacotherapy (nicotine replacement, bupropion SR, or varenicline) to nonpregnant adults who use tobacco (grade A). Combining counseling and medication is most effective." },
  { id: "uspstf-falls", title: "Falls prevention in older adults", org: "USPSTF", year: 2024, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/falls-prevention-community-dwelling-older-adults-interventions", keywords: ["falls", "fall", "balance", "older", "exercise"], text: "Recommend exercise interventions to prevent falls in community-dwelling adults 65 and older at increased risk (grade B). Offer multifactorial interventions selectively (grade C)." },
  { id: "uspstf-aspirin", title: "Aspirin for primary prevention of cardiovascular disease", org: "USPSTF", year: 2022, url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/aspirin-to-prevent-cardiovascular-disease-preventive-medication", keywords: ["aspirin", "primary prevention", "cardiovascular"], text: "Do not start low-dose aspirin for primary prevention in adults 60 and older (grade D). For adults 40 to 59 with a 10-year CVD risk of 10% or more, the decision is individual; net benefit is small (grade C)." },
  { id: "ada-glycemic", title: "Glycemic goals and first-line therapy in type 2 diabetes", org: "American Diabetes Association Standards of Care", year: 2026, url: "https://diabetesjournals.org/care/issue/49/Supplement_1", keywords: ["diabetes", "a1c", "goal", "target", "metformin", "sglt2", "glp-1", "first-line"], text: "An A1c goal below 7% is appropriate for many nonpregnant adults, individualized toward less stringent goals for older adults or those with hypoglycemia risk. Choose therapy by comorbidities: an SGLT2 inhibitor or GLP-1 receptor agonist with proven benefit is recommended for people with ASCVD, heart failure, or CKD regardless of A1c; metformin remains a common foundation." },
  { id: "ada-kidney", title: "Kidney monitoring in diabetes", org: "American Diabetes Association Standards of Care", year: 2026, url: "https://diabetesjournals.org/care/issue/49/Supplement_1", keywords: ["diabetes", "kidney", "uacr", "albumin", "egfr", "ckd"], text: "Assess urine albumin-to-creatinine ratio and eGFR at least yearly in people with type 2 diabetes, and more often with established CKD. Use an ACE inhibitor or ARB for hypertension with albuminuria, and an SGLT2 inhibitor when eGFR is 20 or higher." },
  { id: "accaha-bp", title: "Blood pressure treatment goal", org: "ACC/AHA high blood pressure guideline", year: 2017, url: "https://www.ahajournals.org/doi/10.1161/HYP.0000000000000065", keywords: ["hypertension", "blood pressure", "goal", "target", "130/80"], text: "For adults with confirmed hypertension and known CVD or a 10-year ASCVD risk of 10% or more, the blood pressure goal is below 130/80; this goal is also reasonable for lower-risk adults. First-line agents are thiazide diuretics, ACE inhibitors, ARBs, and calcium channel blockers." },
  { id: "accaha-lipids", title: "Statin intensity by risk group", org: "ACC/AHA cholesterol guideline", year: 2018, url: "https://www.ahajournals.org/doi/10.1161/CIR.0000000000000625", keywords: ["statin", "ldl", "cholesterol", "high-intensity", "moderate-intensity", "ascvd"], text: "High-intensity statin for clinical ASCVD and for LDL of 190 mg/dL or more. Moderate-intensity statin for adults 40 to 75 with diabetes. For primary prevention, use 10-year risk and risk enhancers to guide a shared decision." },
  { id: "cdc-adult-vax", title: "Adult immunization schedule", org: "CDC / ACIP", year: 2025, url: "https://www.cdc.gov/vaccines/hcp/imz-schedules/adult-age.html", keywords: ["vaccine", "immunization", "flu", "influenza", "shingles", "shingrix", "zoster", "pneumococcal", "pneumonia", "rsv", "tdap", "tetanus"], text: "Influenza vaccine every year for everyone 6 months and older. Recombinant zoster vaccine (2 doses) for adults 50 and older and adults 19 and older who are immunocompromised. One pneumococcal conjugate vaccine (PCV20 or PCV21, or PCV15 followed by PPSV23) for adults 50 and older. RSV vaccine for adults 75 and older and adults 50 to 74 at increased risk. Tdap once, then Td or Tdap every 10 years." },
  { id: "kdigo-ckd", title: "CKD evaluation and management", org: "KDIGO", year: 2024, url: "https://kdigo.org/guidelines/ckd-evaluation-and-management/", keywords: ["ckd", "kidney", "egfr", "albuminuria", "sglt2", "ace", "arb"], text: "Classify CKD by cause, GFR category (G1 to G5), and albuminuria category (A1 to A3). Treat with an ACE inhibitor or ARB when albuminuria is moderately or severely increased, and an SGLT2 inhibitor for most adults with CKD and eGFR of 20 or higher." },
  { id: "gina-asthma", title: "Asthma reliever therapy", org: "Global Initiative for Asthma (GINA)", year: 2024, url: "https://ginasthma.org/reports/", keywords: ["asthma", "inhaler", "albuterol", "formoterol", "budesonide", "ics", "reliever"], text: "For adults and adolescents, the preferred reliever is as-needed low-dose ICS-formoterol (Track 1), rather than a short-acting beta agonist alone. SABA-only treatment is not recommended because it raises the risk of severe exacerbations." },
  { id: "aap-aom", title: "Acute otitis media treatment", org: "American Academy of Pediatrics", year: 2013, url: "https://publications.aap.org/pediatrics/article/131/3/e964/30912", keywords: ["otitis", "ear infection", "amoxicillin", "aom", "children"], text: "High-dose amoxicillin (80 to 90 mg/kg/day in 2 divided doses) is first line for acute otitis media when antibiotics are chosen. Observation with close follow-up is an option for nonsevere unilateral AOM in children 6 to 23 months and nonsevere AOM in children 2 years and older. Use amoxicillin-clavulanate if amoxicillin was taken in the last 30 days." },
  { id: "idsa-strep", title: "Group A streptococcal pharyngitis", org: "IDSA", year: 2012, url: "https://academic.oup.com/cid/article/55/10/e86/321183", keywords: ["strep", "pharyngitis", "sore throat", "penicillin", "amoxicillin", "centor"], text: "Confirm group A strep with a rapid antigen test or culture before treating; do not test most adults with clear viral features. Penicillin or amoxicillin for 10 days is first line. For penicillin allergy without anaphylaxis, a first-generation cephalosporin; otherwise clindamycin, azithromycin, or clarithromycin." },
];

const STOP = new Set("a an the of for in on to and or is are what when how should does do i my we with at be by as it this that which who whom patient patients recommend recommendation recommended guideline guidelines".split(" "));

function terms(s: string) {
  return (s.toLowerCase().match(/[a-z0-9][a-z0-9-]*/g) ?? []).filter((t) => !STOP.has(t) && t.length > 1);
}

export function searchEvidence(query: string, k = 3) {
  const q = terms(query);
  if (!q.length) return [];
  const N = EVIDENCE.length;
  const docs = EVIDENCE.map((e) => ({ e, words: terms(`${e.title} ${e.text}`), keys: e.keywords.map((x) => x.toLowerCase()) }));
  const df = (t: string) => docs.filter((d) => d.words.includes(t) || d.keys.some((k2) => k2.split(" ").includes(t))).length;
  const scored = docs.map((d) => {
    let s = 0;
    for (const t of q) {
      const tf = d.words.filter((w) => w === t).length;
      const key = d.keys.some((k2) => k2 === t || k2.split(" ").includes(t)) ? 2 : 0;
      if (!tf && !key) continue;
      const idf = Math.log(1 + (N - df(t) + 0.5) / (df(t) + 0.5));
      s += idf * ((tf * 2.2) / (tf + 1.2) + key);
    }
    for (const kw of d.keys) if (kw.includes(" ") && query.toLowerCase().includes(kw)) s += 3;
    return { entry: d.e, score: s };
  });
  return scored.filter((x) => x.score > 1.5).sort((a, b) => b.score - a.score).slice(0, k);
}

export const GUIDELINE_QUESTION = /\b(recommend|guideline|screen(?:ing)?|how often|when (?:should|to)|goal|target|first[- ]line|interval|uspstf|ada|acip|gina|kdigo|evidence|indicated|eligible|should (?:i|we|she|he|they) (?:start|get|have|be)|vaccines?|immuniz)/i;
