import type { Template } from "../types";

export const SYSTEM_TEMPLATES: Template[] = [
  {
    id: "soap",
    userId: null,
    name: "SOAP note",
    specialty: "General",
    description: "Subjective, Objective, Assessment & Plan. Problem-oriented A&P with codes.",
    style: { verbosity: "standard" },
    sections: [
      { key: "subjective", title: "Subjective", kind: "subjective", format: "paragraph" },
      { key: "objective", title: "Objective", kind: "objective", format: "bullets" },
      { key: "assessment_plan", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "soap_concise",
    userId: null,
    name: "Concise SOAP",
    specialty: "General",
    description: "Short-form SOAP for busy clinics. Pertinent positives and negatives only.",
    style: { verbosity: "concise", abbreviations: true },
    sections: [
      { key: "subjective", title: "S", kind: "subjective", format: "paragraph" },
      { key: "objective", title: "O", kind: "objective", format: "bullets" },
      { key: "assessment_plan", title: "A/P", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "hp",
    userId: null,
    name: "History & Physical",
    specialty: "General",
    description: "Full H&P for new patients and annual visits.",
    style: { verbosity: "detailed" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "pmh", title: "Past Medical History", kind: "pmh", format: "bullets" },
      { key: "meds", title: "Medications", kind: "medications", format: "bullets" },
      { key: "allergies", title: "Allergies", kind: "allergies", format: "bullets" },
      { key: "social", title: "Social History", kind: "social", format: "bullets" },
      { key: "family", title: "Family History", kind: "family", format: "bullets" },
      { key: "ros", title: "Review of Systems", kind: "ros", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Physical Exam", kind: "exam", format: "bullets" },
      { key: "results", title: "Results", kind: "results", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "apso",
    userId: null,
    name: "APSO note",
    specialty: "General",
    description: "Assessment & Plan first so downstream readers see decisions immediately.",
    style: { verbosity: "standard" },
    sections: [
      { key: "assessment_plan", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
      { key: "subjective", title: "Subjective", kind: "subjective", format: "paragraph" },
      { key: "objective", title: "Objective", kind: "objective", format: "bullets" },
    ],
  },
  {
    id: "progress",
    userId: null,
    name: "Chronic care progress note",
    specialty: "Primary Care",
    description: "Interval history per problem, med reconciliation, problem-based plan.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "Interval History", kind: "hpi", format: "paragraph" },
      { key: "meds", title: "Medication Reconciliation", kind: "medications", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Exam", kind: "exam", format: "bullets" },
      { key: "results", title: "Data Reviewed", kind: "results", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "inpatient_progress",
    userId: null,
    name: "Inpatient progress note",
    specialty: "Hospital Medicine",
    description: "Daily SOAP with changes since yesterday; yesterday's problems not addressed today carry forward for you to verify.",
    style: { verbosity: "standard" },
    sections: [
      { key: "subjective", title: "Subjective / Overnight Events", kind: "hpi", format: "paragraph" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Exam", kind: "exam", format: "bullets" },
      { key: "results", title: "Labs and Data", kind: "results", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "discharge",
    userId: null,
    name: "Discharge summary",
    specialty: "Hospital Medicine",
    description: "Assembled from the whole stay: diagnoses, hospital course by problem, med reconciliation, pending results, follow-up.",
    style: { verbosity: "standard" },
    sections: [{ key: "dc_instructions", title: "Discharge Instructions", kind: "patient_instructions", format: "bullets" }],
  },
  {
    id: "onc_followup",
    userId: null,
    name: "Oncology treatment visit",
    specialty: "Oncology",
    description: "On-treatment visit: oncologic history with stage and biomarkers, CTCAE-graded toxicities, ECOG, regimen and cycle, and the treatment decision.",
    style: { verbosity: "standard" },
    sections: [
      { key: "onc_history", title: "Oncologic History", kind: "onc_history", format: "bullets" },
      { key: "interval", title: "Interval History", kind: "hpi", format: "paragraph" },
      { key: "toxicity", title: "Treatment Toxicities", kind: "toxicity", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Physical Exam", kind: "exam", format: "bullets" },
      { key: "results", title: "Labs and Imaging", kind: "results", format: "bullets" },
      { key: "treatment", title: "Treatment Plan", kind: "onc_treatment", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "ed_note",
    userId: null,
    name: "Emergency department note",
    specialty: "Emergency Medicine",
    description: "HPI, ROS, exam, timestamped ED course with re-evaluations, MDM, and disposition.",
    style: { verbosity: "standard" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "ros", title: "Review of Systems", kind: "ros", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Physical Exam", kind: "exam", format: "bullets" },
      { key: "results", title: "Results", kind: "results", format: "bullets" },
      { key: "course", title: "ED Course", kind: "ed_course", format: "bullets" },
      { key: "ap", title: "Medical Decision Making", kind: "assessment_plan", format: "bullets" },
      { key: "dispo", title: "Disposition", kind: "disposition", format: "paragraph" },
    ],
  },
  {
    id: "behavioral",
    userId: null,
    name: "Behavioral health intake",
    specialty: "Behavioral Health",
    description: "Symptoms, safety screen, substance use, mental status exam, plan.",
    style: { verbosity: "standard" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "ros", title: "Psychiatric Review & Safety", kind: "ros", format: "bullets" },
      { key: "social", title: "Social & Substance Use", kind: "social", format: "bullets" },
      { key: "mse", title: "Mental Status Exam", kind: "mental_status", format: "bullets" },
      { key: "risk", title: "Suicide Risk Assessment", kind: "risk", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "bh_psychotherapy",
    userId: null,
    name: "Psychotherapy progress note",
    specialty: "Behavioral Health",
    description: "Interval history, required risk assessment, MSE, interventions, response, plan, and session time for psychotherapy billing.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "Interval History", kind: "hpi", format: "paragraph" },
      { key: "risk", title: "Suicide Risk Assessment", kind: "risk", format: "bullets" },
      { key: "mse", title: "Mental Status Exam", kind: "mental_status", format: "bullets" },
      { key: "interventions", title: "Interventions", kind: "interventions", format: "bullets" },
      { key: "response", title: "Response to Treatment", kind: "response", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
      { key: "time", title: "Session Time", kind: "therapy_time", format: "paragraph" },
    ],
  },
  {
    id: "bh_dap",
    userId: null,
    name: "Therapy note (DAP)",
    specialty: "Behavioral Health",
    description: "Data, Assessment, Plan, with a required risk section and session time.",
    style: { verbosity: "standard" },
    sections: [
      { key: "data", title: "Data", kind: "hpi", format: "paragraph" },
      { key: "risk", title: "Risk Assessment", kind: "risk", format: "bullets" },
      { key: "assessment", title: "Assessment", kind: "assessment", format: "bullets" },
      { key: "plan", title: "Plan", kind: "plan", format: "bullets" },
      { key: "time", title: "Session Time", kind: "therapy_time", format: "paragraph" },
    ],
  },
  {
    id: "bh_birp",
    userId: null,
    name: "Therapy note (BIRP)",
    specialty: "Behavioral Health",
    description: "Behavior, Intervention, Response, Plan, with risk and session time.",
    style: { verbosity: "standard" },
    sections: [
      { key: "behavior", title: "Behavior", kind: "hpi", format: "paragraph" },
      { key: "intervention", title: "Intervention", kind: "interventions", format: "bullets" },
      { key: "response", title: "Response", kind: "response", format: "bullets" },
      { key: "plan", title: "Plan", kind: "plan", format: "bullets" },
      { key: "risk", title: "Risk Assessment", kind: "risk", format: "bullets" },
      { key: "time", title: "Session Time", kind: "therapy_time", format: "paragraph" },
    ],
  },
  {
    id: "psych_med_mgmt",
    userId: null,
    name: "Psychiatry medication management with psychotherapy",
    specialty: "Behavioral Health",
    description: "E/M by medical decision making plus a psychotherapy add-on (90833/90836/90838) when psychotherapy time is documented separately.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "Interval History", kind: "hpi", format: "paragraph" },
      { key: "meds", title: "Current Medications", kind: "medications", format: "bullets" },
      { key: "risk", title: "Suicide Risk Assessment", kind: "risk", format: "bullets" },
      { key: "mse", title: "Mental Status Exam", kind: "mental_status", format: "bullets" },
      { key: "interventions", title: "Psychotherapy Interventions", kind: "interventions", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
      { key: "time", title: "Psychotherapy Time", kind: "therapy_time", format: "paragraph" },
    ],
  },
  {
    id: "bh_girp",
    userId: null,
    name: "Therapy note (GIRP)",
    specialty: "Behavioral Health",
    description: "Goals, Intervention, Response, Plan, with risk and session time.",
    style: { verbosity: "standard" },
    sections: [
      { key: "goals", title: "Goals", kind: "goals", format: "bullets" },
      { key: "intervention", title: "Intervention", kind: "interventions", format: "bullets" },
      { key: "response", title: "Response", kind: "response", format: "bullets" },
      { key: "plan", title: "Plan", kind: "plan", format: "bullets" },
      { key: "risk", title: "Risk Assessment", kind: "risk", format: "bullets" },
      { key: "time", title: "Session Time", kind: "therapy_time", format: "paragraph" },
    ],
  },
  {
    id: "bh_group",
    userId: null,
    name: "Group psychotherapy note",
    specialty: "Behavioral Health",
    description: "One member's note from a group session: group topic, this member's participation only, risk, response, plan. Other members are never named.",
    style: { verbosity: "standard" },
    sections: [
      { key: "topic", title: "Group Session", kind: "group_topic", format: "paragraph" },
      { key: "participation", title: "Member Participation", kind: "group_participation", format: "bullets" },
      { key: "risk", title: "Risk Assessment", kind: "risk", format: "bullets" },
      { key: "interventions", title: "Interventions", kind: "interventions", format: "bullets" },
      { key: "response", title: "Response", kind: "response", format: "bullets" },
      { key: "plan", title: "Plan", kind: "plan", format: "bullets" },
      { key: "time", title: "Session Time", kind: "therapy_time", format: "paragraph" },
    ],
  },
  {
    id: "pt_daily",
    userId: null,
    name: "Physical therapy daily note",
    specialty: "Rehabilitation",
    description: "Treatment note with objective measures, timed interventions with minutes, and 8-minute-rule units billed with modifier GP.",
    style: { verbosity: "standard" },
    sections: [
      { key: "subjective", title: "Subjective", kind: "hpi", format: "paragraph" },
      { key: "measures", title: "Objective Measures", kind: "therapy_measures", format: "bullets" },
      { key: "interventions", title: "Interventions", kind: "therapy_services", format: "bullets" },
      { key: "assessment", title: "Assessment", kind: "response", format: "bullets" },
      { key: "plan", title: "Plan", kind: "plan", format: "bullets" },
    ],
  },
  {
    id: "pt_eval",
    userId: null,
    name: "Physical therapy evaluation",
    specialty: "Rehabilitation",
    description: "Initial or re-evaluation with complexity (97161 to 97164), objective measures, goals, and any treatment given today.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "History", kind: "hpi", format: "paragraph" },
      { key: "pmh", title: "Comorbidities", kind: "pmh", format: "bullets" },
      { key: "measures", title: "Examination", kind: "therapy_measures", format: "bullets" },
      { key: "evaluation", title: "Evaluation", kind: "therapy_eval", format: "paragraph" },
      { key: "goals", title: "Goals", kind: "goals", format: "bullets" },
      { key: "interventions", title: "Treatment Today", kind: "therapy_services", format: "bullets" },
      { key: "plan", title: "Plan of Care", kind: "plan", format: "bullets" },
    ],
  },
  {
    id: "ot_daily",
    userId: null,
    name: "Occupational therapy daily note",
    specialty: "Rehabilitation",
    description: "OT treatment note with timed interventions and 8-minute-rule units billed with modifier GO.",
    style: { verbosity: "standard" },
    sections: [
      { key: "subjective", title: "Subjective", kind: "hpi", format: "paragraph" },
      { key: "measures", title: "Objective Measures", kind: "therapy_measures", format: "bullets" },
      { key: "interventions", title: "Interventions", kind: "therapy_services", format: "bullets" },
      { key: "assessment", title: "Assessment", kind: "response", format: "bullets" },
      { key: "plan", title: "Plan", kind: "plan", format: "bullets" },
    ],
  },
  {
    id: "ob_prenatal",
    userId: null,
    name: "Prenatal visit",
    specialty: "Obstetrics",
    description: "Gestational age by EDD, warning-sign review, fundal height and fetal heart rate, preeclampsia screening, what is due at this gestational age, Z34/Z3A codes, and global OB billing.",
    style: { verbosity: "standard" },
    sections: [
      { key: "pregnancy", title: "Pregnancy", kind: "ob_summary", format: "paragraph" },
      { key: "interval", title: "Interval History", kind: "hpi", format: "paragraph" },
      { key: "warning", title: "Warning Signs", kind: "ob_warning", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "obexam", title: "Prenatal Exam", kind: "ob_exam", format: "bullets" },
      { key: "due", title: "Due at This Gestational Age", kind: "ob_due", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "cardiology_hf",
    userId: null,
    name: "Heart failure follow-up",
    specialty: "Cardiology",
    description: "Interval history, volume status, labs, and a four-pillar GDMT check (ARNI/ACEi/ARB, beta blocker, MRA, SGLT2i) against target doses and safety limits.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "Interval History", kind: "hpi", format: "paragraph" },
      { key: "meds", title: "Medications", kind: "medications", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Physical Exam", kind: "exam", format: "bullets" },
      { key: "results", title: "Labs and Imaging", kind: "results", format: "bullets" },
      { key: "gdmt", title: "Guideline-Directed Medical Therapy", kind: "gdmt", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "peds_well",
    userId: null,
    name: "Well-child visit",
    specialty: "Pediatrics",
    description: "Bright Futures periodicity: screenings due at this age with their codes, immunizations due, anticipatory guidance covered, and the age-based preventive code.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "Interval History", kind: "hpi", format: "paragraph" },
      { key: "vitals", title: "Growth and Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Physical Exam", kind: "exam", format: "bullets" },
      { key: "screens", title: "Screenings", kind: "well_screens", format: "bullets" },
      { key: "imms", title: "Immunizations", kind: "imm_due", format: "bullets" },
      { key: "guidance", title: "Anticipatory Guidance", kind: "guidance", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "awv",
    userId: null,
    name: "Medicare annual wellness visit",
    specialty: "Primary Care",
    description: "Required AWV elements with what is still missing, a personalized screening schedule, advance care planning time (99497-33), and G0438/G0439 with G0444 when allowed.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "Health Risk Assessment and Interval History", kind: "hpi", format: "paragraph" },
      { key: "vitals", title: "Measurements", kind: "vitals", format: "paragraph" },
      { key: "awv", title: "Annual Wellness Visit Elements", kind: "awv", format: "bullets" },
      { key: "schedule", title: "Screening Schedule", kind: "screening_schedule", format: "bullets" },
      { key: "acp", title: "Advance Care Planning", kind: "acp", format: "paragraph" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "ortho_visit",
    userId: null,
    name: "Orthopedic / sports medicine visit",
    specialty: "Orthopedics",
    description: "Mechanism and history, range of motion and strength, special tests with results and side, neurovascular status, imaging, and any injection.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "msk", title: "Musculoskeletal Exam", kind: "msk_exam", format: "bullets" },
      { key: "results", title: "Imaging", kind: "results", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "derm_visit",
    userId: null,
    name: "Dermatology visit",
    specialty: "Dermatology",
    description: "Lesion descriptions with size, color, morphology, and location, ABCDE flags for pigmented lesions, and biopsies or destruction with counts.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "skin", title: "Skin Exam", kind: "skin_exam", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "peds_acute",
    userId: null,
    name: "Pediatric sick visit",
    specialty: "Pediatrics",
    description: "Historian-aware HPI, weight-based dosing reminders, caregiver instructions.",
    style: { verbosity: "standard" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "ros", title: "Review of Systems", kind: "ros", format: "bullets" },
      { key: "allergies", title: "Allergies", kind: "allergies", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Physical Exam", kind: "exam", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
      { key: "instructions", title: "Caregiver Instructions", kind: "patient_instructions", format: "bullets" },
    ],
  },
  {
    id: "msk",
    userId: null,
    name: "Musculoskeletal visit",
    specialty: "Orthopedics / Sports",
    description: "Mechanism of injury, focused exam with special tests, imaging decision, plan.",
    style: { verbosity: "standard" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "ros", title: "Red Flag Review", kind: "ros", format: "bullets" },
      { key: "exam", title: "Focused Exam", kind: "exam", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "vet_equine",
    userId: null,
    name: "Equine exam",
    specialty: "Veterinary",
    description: "Farm or barn call for one horse: signalment, history, TPR and exam, assessment, treatments, owner instructions.",
    style: { verbosity: "standard" },
    sections: [
      { key: "signalment", title: "Signalment", kind: "custom", format: "paragraph", instructions: "Veterinary patient. Name, age, breed, sex, species, owner and barn. Never use human diagnosis codes." },
      { key: "history", title: "History", kind: "hpi", format: "paragraph", instructions: "What the owner or barn manager reported." },
      { key: "exam", title: "Exam", kind: "exam", format: "bullets", instructions: "TPR, mucous membranes, CRT, gut sounds, body condition score, weight, and findings by system." },
      { key: "assessment", title: "Assessment", kind: "assessment", format: "bullets" },
      { key: "plan", title: "Treatments and plan", kind: "plan", format: "bullets", instructions: "Drugs with dose, route and time given (for example xylazine, Banamine, bute), dispensed items, recheck." },
      { key: "instructions", title: "Owner instructions", kind: "patient_instructions", format: "bullets", instructions: "Plain words the owner can follow: stall rest, hand walking, medication times, what to watch for, when to call." },
    ],
  },
  {
    id: "vet_lameness",
    userId: null,
    name: "Lameness exam",
    specialty: "Veterinary",
    description: "AAEP lameness grade, limb, hoof testers, flexions, nerve blocks, imaging, plan and owner instructions.",
    style: { verbosity: "standard" },
    sections: [
      { key: "signalment", title: "Signalment", kind: "custom", format: "paragraph", instructions: "Veterinary patient. Name, age, breed, sex, species, owner and barn." },
      { key: "history", title: "History", kind: "hpi", format: "paragraph" },
      { key: "lameness", title: "Lameness exam", kind: "custom", format: "bullets", instructions: "AAEP grade out of 5 and limb, straight line and circle findings, hoof testers, digital pulses, flexion tests, nerve or joint blocks and response." },
      { key: "exam", title: "Other exam findings", kind: "exam", format: "bullets" },
      { key: "assessment", title: "Assessment", kind: "assessment", format: "bullets" },
      { key: "plan", title: "Treatments and plan", kind: "plan", format: "bullets" },
      { key: "instructions", title: "Owner instructions", kind: "patient_instructions", format: "bullets" },
    ],
  },
  {
    id: "vet_herd",
    userId: null,
    name: "Herd health visit",
    specialty: "Veterinary",
    description: "Food animal or herd call: animal ID and tag, findings, treatments with withdrawal times, plan, owner instructions.",
    style: { verbosity: "standard" },
    sections: [
      { key: "signalment", title: "Animal", kind: "custom", format: "paragraph", instructions: "Veterinary patient. Name or ear tag, species, breed, sex, age, herd or farm, owner." },
      { key: "history", title: "History", kind: "hpi", format: "paragraph" },
      { key: "exam", title: "Findings", kind: "exam", format: "bullets" },
      { key: "assessment", title: "Assessment", kind: "assessment", format: "bullets" },
      { key: "plan", title: "Treatments and withdrawal", kind: "plan", format: "bullets", instructions: "Drug, dose, route, and any meat or milk withdrawal time exactly as stated. Never invent a withdrawal time." },
      { key: "instructions", title: "Owner instructions", kind: "patient_instructions", format: "bullets" },
    ],
  },
  {
    id: "vet_repro",
    userId: null,
    name: "Reproductive exam",
    specialty: "Veterinary",
    description: "Palpation or ultrasound per mare or cow: ovaries, follicles, CL, uterus, pregnancy status and days, breeding plan.",
    style: { verbosity: "standard" },
    sections: [
      { key: "signalment", title: "Animal", kind: "custom", format: "paragraph", instructions: "Veterinary patient." },
      { key: "history", title: "Breeding history", kind: "hpi", format: "paragraph" },
      { key: "exam", title: "Reproductive findings", kind: "exam", format: "bullets", instructions: "Left and right ovary, follicle sizes, corpus luteum, uterine edema or fluid, pregnancy status and days." },
      { key: "assessment", title: "Assessment", kind: "assessment", format: "bullets" },
      { key: "plan", title: "Breeding plan", kind: "plan", format: "bullets" },
      { key: "instructions", title: "Owner instructions", kind: "patient_instructions", format: "bullets" },
    ],
  },
  {
    id: "vet_small_soap",
    userId: null,
    name: "Small animal SOAP",
    specialty: "Veterinary",
    description: "Dog or cat visit: subjective, objective with TPR and weight, assessment, plan and client instructions.",
    style: { verbosity: "standard" },
    sections: [
      { key: "signalment", title: "Signalment", kind: "custom", format: "paragraph", instructions: "Veterinary patient." },
      { key: "subjective", title: "Subjective", kind: "subjective", format: "paragraph" },
      { key: "objective", title: "Objective", kind: "objective", format: "bullets" },
      { key: "assessment", title: "Assessment", kind: "assessment", format: "bullets" },
      { key: "plan", title: "Plan", kind: "plan", format: "bullets" },
      { key: "instructions", title: "Client instructions", kind: "patient_instructions", format: "bullets" },
    ],
  },
];

export const VET_SPECIALTIES = ["Veterinary: Large animal", "Veterinary: Equine", "Veterinary: Mixed", "Veterinary: Small animal"];

export function isVetSpecialty(s: string | null | undefined) {
  return /^veterinary/i.test(s ?? "");
}

export function vetDefaultTemplate(specialty: string) {
  if (/small/i.test(specialty)) return "vet_small_soap";
  if (/large/i.test(specialty)) return "vet_herd";
  return "vet_equine";
}

export function systemTemplate(id: string) {
  return SYSTEM_TEMPLATES.find((t) => t.id === id);
}
