import type { Template } from "../types";

export const SYSTEM_TEMPLATES: Template[] = [
  {
    id: "soap",
    userId: null,
    name: "SOAP note",
    specialty: "General",
    description: "Subjective, Objective, Assessment & Plan. Problem-oriented A&P with codes.",
    style: { verbosity: "standard" },
    sections: [
      { key: "subjective", title: "Subjective", kind: "subjective", format: "paragraph" },
      { key: "objective", title: "Objective", kind: "objective", format: "bullets" },
      { key: "assessment_plan", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "soap_concise",
    userId: null,
    name: "Concise SOAP",
    specialty: "General",
    description: "Short-form SOAP for busy clinics. Pertinent positives and negatives only.",
    style: { verbosity: "concise", abbreviations: true },
    sections: [
      { key: "subjective", title: "S", kind: "subjective", format: "paragraph" },
      { key: "objective", title: "O", kind: "objective", format: "bullets" },
      { key: "assessment_plan", title: "A/P", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "hp",
    userId: null,
    name: "History & Physical",
    specialty: "General",
    description: "Full H&P for new patients and annual visits.",
    style: { verbosity: "detailed" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "pmh", title: "Past Medical History", kind: "pmh", format: "bullets" },
      { key: "meds", title: "Medications", kind: "medications", format: "bullets" },
      { key: "allergies", title: "Allergies", kind: "allergies", format: "bullets" },
      { key: "social", title: "Social History", kind: "social", format: "bullets" },
      { key: "family", title: "Family History", kind: "family", format: "bullets" },
      { key: "ros", title: "Review of Systems", kind: "ros", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Physical Exam", kind: "exam", format: "bullets" },
      { key: "results", title: "Results", kind: "results", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "apso",
    userId: null,
    name: "APSO note",
    specialty: "General",
    description: "Assessment & Plan first so downstream readers see decisions immediately.",
    style: { verbosity: "standard" },
    sections: [
      { key: "assessment_plan", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
      { key: "subjective", title: "Subjective", kind: "subjective", format: "paragraph" },
      { key: "objective", title: "Objective", kind: "objective", format: "bullets" },
    ],
  },
  {
    id: "progress",
    userId: null,
    name: "Chronic care progress note",
    specialty: "Primary Care",
    description: "Interval history per problem, med reconciliation, problem-based plan.",
    style: { verbosity: "standard" },
    sections: [
      { key: "hpi", title: "Interval History", kind: "hpi", format: "paragraph" },
      { key: "meds", title: "Medication Reconciliation", kind: "medications", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Exam", kind: "exam", format: "bullets" },
      { key: "results", title: "Data Reviewed", kind: "results", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "behavioral",
    userId: null,
    name: "Behavioral health intake",
    specialty: "Behavioral Health",
    description: "Symptoms, safety screen, substance use, mental status exam, plan.",
    style: { verbosity: "standard" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "ros", title: "Psychiatric Review & Safety", kind: "ros", format: "bullets" },
      { key: "social", title: "Social & Substance Use", kind: "social", format: "bullets" },
      { key: "mse", title: "Mental Status Exam", kind: "mental_status", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
  {
    id: "peds_acute",
    userId: null,
    name: "Pediatric sick visit",
    specialty: "Pediatrics",
    description: "Historian-aware HPI, weight-based dosing reminders, caregiver instructions.",
    style: { verbosity: "standard" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "ros", title: "Review of Systems", kind: "ros", format: "bullets" },
      { key: "allergies", title: "Allergies", kind: "allergies", format: "bullets" },
      { key: "vitals", title: "Vitals", kind: "vitals", format: "paragraph" },
      { key: "exam", title: "Physical Exam", kind: "exam", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
      { key: "instructions", title: "Caregiver Instructions", kind: "patient_instructions", format: "bullets" },
    ],
  },
  {
    id: "msk",
    userId: null,
    name: "Musculoskeletal visit",
    specialty: "Orthopedics / Sports",
    description: "Mechanism of injury, focused exam with special tests, imaging decision, plan.",
    style: { verbosity: "standard" },
    sections: [
      { key: "cc", title: "Chief Complaint", kind: "chief_complaint", format: "paragraph" },
      { key: "hpi", title: "History of Present Illness", kind: "hpi", format: "paragraph" },
      { key: "ros", title: "Red Flag Review", kind: "ros", format: "bullets" },
      { key: "exam", title: "Focused Exam", kind: "exam", format: "bullets" },
      { key: "ap", title: "Assessment & Plan", kind: "assessment_plan", format: "bullets" },
    ],
  },
];

export function systemTemplate(id: string) {
  return SYSTEM_TEMPLATES.find((t) => t.id === id);
}
