import type { Chart, Speaker } from "../types";

export interface DemoLine {
  s: Speaker;
  t: string;
  lang?: string;
}

export interface DemoPatient {
  key: string;
  mrn: string;
  name: string;
  dob: string;
  sex: "F" | "M";
  pronouns: string;
  language: string;
  chart: Chart;
  visit: { time: string; type: "new" | "follow-up" | "acute" | "annual" | "telehealth"; reason: string; template: string; outputLang?: string };
  script: DemoLine[];
}

export const DEMO_PATIENTS: DemoPatient[] = [
  {
    key: "gonzalez",
    mrn: "100482",
    name: "Maria Gonzalez",
    dob: "1968-03-14",
    sex: "F",
    pronouns: "she/her",
    language: "en",
    chart: {
      problems: [
        { name: "Essential hypertension", icd10: "I10", since: "2016" },
        { name: "Type 2 diabetes mellitus", icd10: "E11.9", since: "2019" },
        { name: "Hyperlipidemia", icd10: "E78.5", since: "2019" },
      ],
      medications: [
        { name: "lisinopril", dose: "10 mg", frequency: "daily" },
        { name: "metformin", dose: "500 mg", frequency: "twice daily" },
        { name: "atorvastatin", dose: "20 mg", frequency: "at bedtime" },
      ],
      allergies: [{ substance: "sulfa", reaction: "hives" }],
      vitals: { BP: "146/92", Weight: "184 lb", BMI: "31.6" },
      labs: [
        { name: "Hemoglobin A1c", value: "8.4 %", date: "2026-09-10", flag: "high" },
        { name: "LDL", value: "96 mg/dL", date: "2026-09-10", flag: "normal" },
        { name: "eGFR", value: "58 mL/min/1.73m²", date: "2026-09-10", flag: "low" },
      ],
      egfr: 58,
      social: ["Never smoker", "Works as a school administrator"],
      smoking: "never",
      screenings: [{ name: "Screening mammogram", date: "2025-11-04", result: "BI-RADS 1" }, { name: "Colonoscopy", date: "2019-05-20", result: "Normal" }, { name: "PHQ-9", date: "2026-06-12", result: "3" }],
      immunizations: [{ name: "Influenza vaccine", date: "2025-10-15" }],
      priorVisits: [
        { date: "2026-06-12", summary: "HTN and DM follow-up. BP 144/90. A1c 7.9.", plan: ["Recheck A1c in 3 months", "Home BP log", "Diabetic eye exam referral"] },
      ],
    },
    visit: { time: "08:30", type: "follow-up", reason: "Diabetes and blood pressure follow-up", template: "soap" },
    script: [
      { s: "clinician", t: "Good morning Maria, good to see you again. How have things been since June?" },
      { s: "patient", t: "Pretty good overall, but I've been really tired the last couple of months, and I'm thirsty all the time." },
      { s: "clinician", t: "Okay. Your A1c came back at 8.4, which is up from 7.9 last time. How are you doing with the metformin?" },
      { s: "patient", t: "I take the metformin 500 milligrams twice a day, but honestly it upsets my stomach, so sometimes I skip the evening dose." },
      { s: "clinician", t: "That's really helpful to know. Any nausea or diarrhea with it?" },
      { s: "patient", t: "Some diarrhea in the mornings, yeah." },
      { s: "clinician", t: "And what have your home blood pressure readings looked like?" },
      { s: "patient", t: "My readings at home have been in the 150s over 90s most days." },
      { s: "clinician", t: "Today your blood pressure is 152 over 94, and your pulse is 78. Are you still taking the lisinopril 10 milligrams every day?" },
      { s: "patient", t: "Yes, every morning." },
      { s: "clinician", t: "Any headaches, chest pain, or shortness of breath?" },
      { s: "patient", t: "No, none of that." },
      { s: "clinician", t: "Any numbness or tingling in your feet?" },
      { s: "patient", t: "No." },
      { s: "clinician", t: "Any allergies to medications besides the sulfa?" },
      { s: "patient", t: "No, just sulfa, it gives me hives." },
      { s: "clinician", t: "Let me take a listen. Take a deep breath for me." },
      { s: "clinician", t: "Lungs sound clear on both sides. Heart sounds regular, no murmurs." },
      { s: "clinician", t: "Your feet look good, sensation is intact with the monofilament, and pulses are normal." },
      { s: "clinician", t: "So here's the plan. Your blood pressure is still above goal, so I want to increase the lisinopril to 20 milligrams daily." },
      { s: "clinician", t: "For the diabetes, I think the sugars are not at goal partly because of the missed doses. Let's switch you to metformin extended release 1000 milligrams once daily with dinner, which is easier on the stomach." },
      { s: "clinician", t: "I'd also like to start empagliflozin 10 milligrams daily, which helps with sugars and protects your kidneys." },
      { s: "clinician", t: "We'll check a basic metabolic panel in two weeks because of the lisinopril change, and a urine microalbumin today." },
      { s: "clinician", t: "I want you to cut back on salt and keep logging your blood pressure at home." },
      { s: "clinician", t: "I'd also like to refer you to a diabetes educator to go over meal planning." },
      { s: "clinician", t: "If you get dizzy or lightheaded when you stand up, call the office." },
      { s: "clinician", t: "Let's follow up in 3 months with a repeat A1c. Any questions for me?" },
      { s: "patient", t: "Will the new medicine make me pee more?" },
      { s: "clinician", t: "It can a little, so stay hydrated. That's normal." },
      { s: "patient", t: "Okay, thank you doctor." },
    ],
  },
  {
    key: "carter",
    mrn: "100517",
    name: "James Carter",
    dob: "1992-07-02",
    sex: "M",
    pronouns: "he/him",
    language: "en",
    chart: {
      problems: [{ name: "Seasonal allergic rhinitis", icd10: "J30.2" }],
      medications: [{ name: "cetirizine", dose: "10 mg", frequency: "daily as needed" }],
      allergies: [],
      social: ["Former smoker, quit 2019"],
      priorVisits: [{ date: "2025-11-03", summary: "Annual physical. No acute issues.", plan: ["Flu vaccine given"] }],
    },
    visit: { time: "09:15", type: "acute", reason: "Cough and congestion", template: "soap" },
    script: [
      { s: "clinician", t: "Hi James, what brings you in today?" },
      { s: "patient", t: "I've had this cough for about six days now, and I'm really congested." },
      { s: "clinician", t: "Is the cough dry or are you bringing anything up?" },
      { s: "patient", t: "Mostly dry, but it's worse at night and keeps me up." },
      { s: "clinician", t: "Have you had any fevers?" },
      { s: "patient", t: "Yeah, I had a fever of 101 the first two days but it's gone now." },
      { s: "clinician", t: "Any shortness of breath or chest pain?" },
      { s: "patient", t: "No, not really." },
      { s: "clinician", t: "Any sore throat or ear pain?" },
      { s: "patient", t: "A little bit of a sore throat." },
      { s: "patient", t: "My kids had the same thing last week." },
      { s: "clinician", t: "Have you tried anything for it?" },
      { s: "patient", t: "I tried some Mucinex and honey, and the honey seems to help a bit." },
      { s: "clinician", t: "Do you smoke?" },
      { s: "patient", t: "No, I quit smoking in 2019." },
      { s: "clinician", t: "Your temperature today is 99.1 and oxygen is 98 percent. Let me take a look." },
      { s: "clinician", t: "Your throat is a little red but no exudate. Ears look normal." },
      { s: "clinician", t: "Lungs sound clear, no wheezing or crackles." },
      { s: "clinician", t: "I think this is most likely a viral upper respiratory infection, and antibiotics won't help here." },
      { s: "clinician", t: "I'm going to prescribe benzonatate 100 milligrams three times a day as needed for the cough so you can sleep." },
      { s: "clinician", t: "Keep up the honey, drink plenty of fluids, and try a humidifier at night." },
      { s: "clinician", t: "If you get a fever over 102, trouble breathing, or it's not better in 10 days, come back and see us." },
      { s: "clinician", t: "Any other questions?" },
      { s: "patient", t: "No, that's it. Thanks." },
    ],
  },
  {
    key: "shah",
    mrn: "100533",
    name: "Priya Shah",
    dob: "1981-11-20",
    sex: "F",
    pronouns: "she/her",
    language: "en",
    chart: {
      problems: [{ name: "Hypothyroidism", icd10: "E03.9", since: "2015" }],
      medications: [{ name: "levothyroxine", dose: "75 mcg", frequency: "daily" }],
      allergies: [{ substance: "codeine", reaction: "nausea" }],
      priorVisits: [{ date: "2026-02-18", summary: "Hypothyroidism follow-up. TSH 2.1.", plan: ["Continue levothyroxine 75 mcg"] }],
    },
    visit: { time: "10:00", type: "acute", reason: "Low back pain", template: "soap" },
    script: [
      { s: "clinician", t: "Hi Priya, I hear your back has been bothering you." },
      { s: "patient", t: "Yes, my lower back has been hurting for about two weeks, ever since I was moving boxes at home." },
      { s: "clinician", t: "On a scale of 1 to 10, how bad is it?" },
      { s: "patient", t: "Most days it's a 6 out of 10. It's a sharp pain and it shoots down my left leg sometimes." },
      { s: "clinician", t: "What makes it better or worse?" },
      { s: "patient", t: "It's worse when I sit for a long time, and it gets better with walking. Ibuprofen helps a little." },
      { s: "clinician", t: "Any numbness or weakness in your legs?" },
      { s: "patient", t: "No." },
      { s: "clinician", t: "Any trouble controlling your bladder or bowels, or any fevers?" },
      { s: "patient", t: "No, nothing like that." },
      { s: "clinician", t: "Okay, let me examine your back. Tell me if this hurts." },
      { s: "clinician", t: "You're tender over the left lower paraspinal muscles. Straight leg raise is positive on the left at about 45 degrees." },
      { s: "clinician", t: "Strength is 5 out of 5 in both legs and reflexes are normal and symmetric." },
      { s: "clinician", t: "This looks like a lumbar strain with some sciatica, and I'm not concerned about anything serious given your exam." },
      { s: "clinician", t: "We don't need an x-ray right now." },
      { s: "clinician", t: "I'm going to prescribe naproxen 500 milligrams twice a day with food for two weeks, and cyclobenzaprine 5 milligrams at bedtime as needed for spasms." },
      { s: "clinician", t: "I'd also like to refer you to physical therapy." },
      { s: "clinician", t: "Try to stay active, use heat on your back, and avoid lifting anything heavy for now." },
      { s: "clinician", t: "If you develop numbness, weakness, or any trouble with your bladder, go to the ER right away." },
      { s: "clinician", t: "Let's follow up in 4 weeks. Any questions?" },
      { s: "patient", t: "Can I keep going to yoga?" },
      { s: "clinician", t: "Gentle stretching is fine, just skip deep forward bends for now." },
    ],
  },
  {
    key: "kim",
    mrn: "100561",
    name: "Daniel Kim",
    dob: "1997-01-09",
    sex: "M",
    pronouns: "he/him",
    language: "en",
    chart: {
      problems: [],
      medications: [],
      allergies: [],
      social: ["Software engineer"],
      priorVisits: [],
    },
    visit: { time: "10:45", type: "new", reason: "Anxiety and trouble sleeping", template: "soap" },
    script: [
      { s: "clinician", t: "Hi Daniel, welcome. What would you like to talk about today?" },
      { s: "patient", t: "I've been feeling anxious all the time for the past three months, and I can't sleep." },
      { s: "clinician", t: "Tell me more about the anxiety." },
      { s: "patient", t: "I'm on edge at work, my mind races at night, and I've had a couple of panic attacks where my heart is racing." },
      { s: "clinician", t: "How is your sleep?" },
      { s: "patient", t: "I have trouble falling asleep, maybe four or five hours a night, and I'm tired during the day." },
      { s: "clinician", t: "Any low mood or losing interest in things you enjoy?" },
      { s: "patient", t: "Sometimes I feel down, but I still enjoy playing basketball on weekends." },
      { s: "clinician", t: "Any thoughts of hurting yourself or that you'd be better off dead?" },
      { s: "patient", t: "No, never." },
      { s: "clinician", t: "How much alcohol do you drink?" },
      { s: "patient", t: "I drink maybe three or four beers on the weekend." },
      { s: "clinician", t: "Any caffeine?" },
      { s: "patient", t: "Probably three or four coffees a day." },
      { s: "clinician", t: "Your blood pressure is 128 over 82 and heart rate is 88." },
      { s: "clinician", t: "You appear anxious but in no distress. Your mood seems anxious with a full range of affect, and your thought process is logical." },
      { s: "clinician", t: "I think this is most consistent with generalized anxiety disorder with associated insomnia." },
      { s: "clinician", t: "I'd like to start sertraline 25 milligrams daily for one week, then increase to 50 milligrams daily." },
      { s: "clinician", t: "I also recommend talk therapy, so I'm going to refer you to behavioral health." },
      { s: "clinician", t: "Try to cut back on caffeine, especially after noon, and keep screens out of the bedroom." },
      { s: "clinician", t: "If you ever have thoughts of hurting yourself, call or text 988 or go to the emergency room." },
      { s: "clinician", t: "Let's follow up in 4 weeks to see how the medication is working. Any questions for me?" },
      { s: "patient", t: "How long until it starts working?" },
      { s: "clinician", t: "Usually two to four weeks, and side effects like mild nausea usually fade in the first week." },
    ],
  },
  {
    key: "ramirez",
    mrn: "100588",
    name: "Sofia Ramirez",
    dob: "2020-05-30",
    sex: "F",
    pronouns: "she/her",
    language: "es",
    chart: {
      problems: [],
      medications: [],
      allergies: [{ substance: "penicillin", reaction: "rash" }],
      priorVisits: [{ date: "2026-05-28", summary: "Well child check, age 6. Growth normal.", plan: ["Vaccines up to date"] }],
    },
    visit: { time: "11:30", type: "acute", reason: "Ear pain and fever", template: "soap", outputLang: "es" },
    script: [
      { s: "clinician", t: "Hi Sofia, hi mom. I understand she has ear pain?" },
      { s: "patient", t: "Yes, her right ear has been hurting for two days and she keeps pulling at her ear." },
      { s: "clinician", t: "Has she had a fever?" },
      { s: "patient", t: "Yes, a fever of 102 last night. I gave her Tylenol and it helped." },
      { s: "clinician", t: "Any cough or runny nose?" },
      { s: "patient", t: "A runny nose for about a week." },
      { s: "clinician", t: "Any vomiting or diarrhea?" },
      { s: "patient", t: "No." },
      { s: "clinician", t: "Her temperature today is 100.9. Let me take a look in her ears." },
      { s: "clinician", t: "Her right eardrum is red and bulging. The left eardrum looks normal. Throat looks fine and lungs are clear." },
      { s: "clinician", t: "This is a right middle ear infection. Let's start amoxicillin twice a day for 10 days." },
      { s: "patient", t: "Wait, she's allergic to penicillin, she got a rash last time." },
      { s: "clinician", t: "Thank you for telling me. Let's skip the amoxicillin and start azithromycin once a day for 5 days instead." },
      { s: "clinician", t: "You can keep giving Tylenol or ibuprofen for pain and fever." },
      { s: "clinician", t: "If she has a fever over 102 for more than two more days, swelling behind the ear, or seems very sleepy, bring her back right away." },
      { s: "clinician", t: "Let's recheck her ear in 2 weeks. Any questions?" },
      { s: "patient", t: "Can she go to school tomorrow?" },
      { s: "clinician", t: "Once she has no fever for 24 hours, she can go back." },
    ],
  },
  {
    key: "morales",
    mrn: "100603",
    name: "Ana Morales",
    dob: "1954-10-12",
    sex: "F",
    pronouns: "she/her",
    language: "es",
    chart: {
      problems: [{ name: "Chronic obstructive pulmonary disease", icd10: "J44.9", since: "2018" }],
      medications: [{ name: "albuterol", dose: "2 puffs", frequency: "every 4 hours as needed" }, { name: "budesonide-formoterol", dose: "2 puffs", frequency: "twice daily" }],
      allergies: [],
      social: ["Former smoker, 30 pack-years, quit 2015"],
      smoking: "former",
      screenings: [{ name: "FIT", date: "2026-02-10", result: "Negative" }],
      priorVisits: [{ date: "2026-07-02", summary: "COPD follow-up. Stable.", plan: ["Continue Symbicort", "Pneumonia vaccine due"] }],
    },
    visit: { time: "13:00", type: "follow-up", reason: "COPD follow-up (Spanish interpreter)", template: "soap", outputLang: "es" },
    script: [
      { s: "clinician", t: "Hi Mrs. Morales, how has your breathing been since July?", lang: "en" },
      { s: "other", t: "Hola señora Morales, ¿cómo ha estado su respiración desde julio?", lang: "es" },
      { s: "patient", t: "Más o menos. Me falta el aire cuando camino y tengo tos en las mañanas.", lang: "es" },
      { s: "other", t: "So-so. I get short of breath when I walk and I have a cough in the mornings.", lang: "en" },
      { s: "clinician", t: "How often are you using the albuterol rescue inhaler?", lang: "en" },
      { s: "other", t: "¿Con qué frecuencia usa el inhalador de rescate albuterol?", lang: "es" },
      { s: "patient", t: "Lo uso cada cuatro horas, casi todos los días.", lang: "es" },
      { s: "other", t: "She uses it every six hours, almost every day.", lang: "en" },
      { s: "clinician", t: "Any fever or chest pain?", lang: "en" },
      { s: "other", t: "¿Ha tenido fiebre o dolor de pecho?", lang: "es" },
      { s: "patient", t: "No, nada de eso.", lang: "es" },
      { s: "other", t: "No, none of that.", lang: "en" },
      { s: "clinician", t: "Her oxygen is 93 percent today. Let me listen to her lungs.", lang: "en" },
      { s: "clinician", t: "I hear some wheezing on both sides, but no crackles.", lang: "en" },
      { s: "clinician", t: "Her COPD is not well controlled. Let's continue the Symbicort and I'd like to add tiotropium once daily.", lang: "en" },
      { s: "other", t: "Su EPOC no está bien controlado. Vamos a continuar el Symbicort y agregar tiotropio una vez al día.", lang: "es" },
      { s: "clinician", t: "I also want to order a chest x-ray and give the pneumonia vaccine today.", lang: "en" },
      { s: "other", t: "También quiere ordenar una radiografía de pecho y ponerle la vacuna contra la neumonía hoy.", lang: "es" },
      { s: "clinician", t: "If her breathing gets worse or her lips turn blue, go to the emergency room. Follow up in 4 weeks.", lang: "en" },
      { s: "other", t: "Si su respiración empeora o sus labios se ponen azules, vaya a la sala de emergencias. Regrese en 4 semanas.", lang: "es" },
    ],
  },
];