import type { Chart, Speaker } from "../types";

export interface DemoLine {
  s: Speaker;
  t: string;
  lang?: string;
}

export interface DemoPatient {
  key: string;
  mrn: string;
  name: string;
  dob: string;
  sex: "F" | "M";
  pronouns: string;
  language: string;
  chart: Chart;
  visit: { time: string; type: "new" | "follow-up" | "acute" | "annual" | "telehealth"; reason: string; template: string; outputLang?: string };
  script: DemoLine[];
}

export const DEMO_PATIENTS: DemoPatient[] = [
  {
    key: "gonzalez",
    mrn: "100482",
    name: "Maria Gonzalez",
    dob: "1968-03-14",
    sex: "F",
    pronouns: "she/her",
    language: "en",
    chart: {
      problems: [
        { name: "Essential hypertension", icd10: "I10", since: "2016" },
        { name: "Type 2 diabetes mellitus", icd10: "E11.9", since: "2019" },
        { name: "Hyperlipidemia", icd10: "E78.5", since: "2019" },
      ],
      medications: [
        { name: "lisinopril", dose: "10 mg", frequency: "daily" },
        { name: "metformin", dose: "500 mg", frequency: "twice daily" },
        { name: "atorvastatin", dose: "20 mg", frequency: "at bedtime" },
      ],
      allergies: [{ substance: "sulfa", reaction: "hives" }],
      vitals: { BP: "146/92", Weight: "184 lb", BMI: "31.6" },
      labs: [
        { name: "Hemoglobin A1c", value: "8.4 %", date: "2026-09-10", flag: "high" },
        { name: "LDL", value: "96 mg/dL", date: "2026-09-10", flag: "normal" },
        { name: "eGFR", value: "58 mL/min/1.73m²", date: "2026-09-10", flag: "low" },
      ],
      egfr: 58,
      social: ["Never smoker", "Works as a school administrator"],
      smoking: "never",
      screenings: [{ name: "Screening mammogram", date: "2025-11-04", result: "BI-RADS 1" }, { name: "Colonoscopy", date: "2019-05-20", result: "Normal" }, { name: "PHQ-9", date: "2026-06-12", result: "3" }],
      immunizations: [{ name: "Influenza vaccine", date: "2025-10-15" }],
      priorVisits: [
        { date: "2026-06-12", summary: "HTN and DM follow-up. BP 144/90. A1c 7.9.", plan: ["Recheck A1c in 3 months", "Home BP log", "Diabetic eye exam referral"] },
      ],
    },
    visit: { time: "08:30", type: "follow-up", reason: "Diabetes and blood pressure follow-up", template: "soap" },
    script: [
      { s: "clinician", t: "Good morning Maria, good to see you again. How have things been since June?" },
      { s: "patient", t: "Pretty good overall, but I've been really tired the last couple of months, and I'm thirsty all the time." },
      { s: "clinician", t: "Okay. Your A1c came back at 8.4, which is up from 7.9 last time. How are you doing with the metformin?" },
      { s: "patient", t: "I take the metformin 500 milligrams twice a day, but honestly it upsets my stomach, so sometimes I skip the evening dose." },
      { s: "clinician", t: "That's really helpful to know. Any nausea or diarrhea with it?" },
      { s: "patient", t: "Some diarrhea in the mornings, yeah." },
      { s: "clinician", t: "And what have your home blood pressure readings looked like?" },
      { s: "patient", t: "My readings at home have been in the 150s over 90s most days." },
      { s: "clinician", t: "Today your blood pressure is 152 over 94, and your pulse is 78. Are you still taking the lisinopril 10 milligrams every day?" },
      { s: "patient", t: "Yes, every morning." },
      { s: "clinician", t: "Any headaches, chest pain, or shortness of breath?" },
      { s: "patient", t: "No, none of that." },
      { s: "clinician", t: "Any numbness or tingling in your feet?" },
      { s: "patient", t: "No." },
      { s: "clinician", t: "Any allergies to medications besides the sulfa?" },
      { s: "patient", t: "No, just sulfa, it gives me hives." },
      { s: "clinician", t: "Let me take a listen. Take a deep breath for me." },
      { s: "clinician", t: "Lungs sound clear on both sides. Heart sounds regular, no murmurs." },
      { s: "clinician", t: "Your feet look good, sensation is intact with the monofilament, and pulses are normal." },
      { s: "clinician", t: "So here's the plan. Your blood pressure is still above goal, so I want to increase the lisinopril to 20 milligrams daily." },
      { s: "clinician", t: "For the diabetes, I think the sugars are not at goal partly because of the missed doses. Let's switch you to metformin extended release 1000 milligrams once daily with dinner, which is easier on the stomach." },
      { s: "clinician", t: "I'd also like to start empagliflozin 10 milligrams daily, which helps with sugars and protects your kidneys." },
      { s: "clinician", t: "We'll check a basic metabolic panel in two weeks because of the lisinopril change, and a urine microalbumin today." },
      { s: "clinician", t: "I want you to cut back on salt and keep logging your blood pressure at home." },
      { s: "clinician", t: "I'd also like to refer you to a diabetes educator to go over meal planning." },
      { s: "clinician", t: "If you get dizzy or lightheaded when you stand up, call the office." },
      { s: "clinician", t: "Let's follow up in 3 months with a repeat A1c. Any questions for me?" },
      { s: "patient", t: "Will the new medicine make me pee more?" },
      { s: "clinician", t: "It can a little, so stay hydrated. That's normal." },
      { s: "patient", t: "Okay, thank you doctor." },
    ],
  },
  {
    key: "carter",
    mrn: "100517",
    name: "James Carter",
    dob: "1992-07-02",
    sex: "M",
    pronouns: "he/him",
    language: "en",
    chart: {
      problems: [{ name: "Seasonal allergic rhinitis", icd10: "J30.2" }],
      medications: [{ name: "cetirizine", dose: "10 mg", frequency: "daily as needed" }],
      allergies: [],
      social: ["Former smoker, quit 2019"],
      priorVisits: [{ date: "2025-11-03", summary: "Annual physical. No acute issues.", plan: ["Flu vaccine given"] }],
    },
    visit: { time: "09:15", type: "acute", reason: "Cough and congestion", template: "soap" },
    script: [
      { s: "clinician", t: "Hi James, what brings you in today?" },
      { s: "patient", t: "I've had this cough for about six days now, and I'm really congested." },
      { s: "clinician", t: "Is the cough dry or are you bringing anything up?" },
      { s: "patient", t: "Mostly dry, but it's worse at night and keeps me up." },
      { s: "clinician", t: "Have you had any fevers?" },
      { s: "patient", t: "Yeah, I had a fever of 101 the first two days but it's gone now." },
      { s: "clinician", t: "Any shortness of breath or chest pain?" },
      { s: "patient", t: "No, not really." },
      { s: "clinician", t: "Any sore throat or ear pain?" },
      { s: "patient", t: "A little bit of a sore throat." },
      { s: "patient", t: "My kids had the same thing last week." },
      { s: "clinician", t: "Have you tried anything for it?" },
      { s: "patient", t: "I tried some Mucinex and honey, and the honey seems to help a bit." },
      { s: "clinician", t: "Do you smoke?" },
      { s: "patient", t: "No, I quit smoking in 2019." },
      { s: "clinician", t: "Your temperature today is 99.1 and oxygen is 98 percent. Let me take a look." },
      { s: "clinician", t: "Your throat is a little red but no exudate. Ears look normal." },
      { s: "clinician", t: "Lungs sound clear, no wheezing or crackles." },
      { s: "clinician", t: "I think this is most likely a viral upper respiratory infection, and antibiotics won't help here." },
      { s: "clinician", t: "I'm going to prescribe benzonatate 100 milligrams three times a day as needed for the cough so you can sleep." },
      { s: "clinician", t: "Keep up the honey, drink plenty of fluids, and try a humidifier at night." },
      { s: "clinician", t: "If you get a fever over 102, trouble breathing, or it's not better in 10 days, come back and see us." },
      { s: "clinician", t: "Any other questions?" },
      { s: "patient", t: "No, that's it. Thanks." },
    ],
  },
  {
    key: "shah",
    mrn: "100533",
    name: "Priya Shah",
    dob: "1981-11-20",
    sex: "F",
    pronouns: "she/her",
    language: "en",
    chart: {
      problems: [{ name: "Hypothyroidism", icd10: "E03.9", since: "2015" }],
      medications: [{ name: "levothyroxine", dose: "75 mcg", frequency: "daily" }],
      allergies: [{ substance: "codeine", reaction: "nausea" }],
      priorVisits: [{ date: "2026-02-18", summary: "Hypothyroidism follow-up. TSH 2.1.", plan: ["Continue levothyroxine 75 mcg"] }],
    },
    visit: { time: "10:00", type: "acute", reason: "Low back pain", template: "soap" },
    script: [
      { s: "clinician", t: "Hi Priya, I hear your back has been bothering you." },
      { s: "patient", t: "Yes, my lower back has been hurting for about two weeks, ever since I was moving boxes at home." },
      { s: "clinician", t: "On a scale of 1 to 10, how bad is it?" },
      { s: "patient", t: "Most days it's a 6 out of 10. It's a sharp pain and it shoots down my left leg sometimes." },
      { s: "clinician", t: "What makes it better or worse?" },
      { s: "patient", t: "It's worse when I sit for a long time, and it gets better with walking. Ibuprofen helps a little." },
      { s: "clinician", t: "Any numbness or weakness in your legs?" },
      { s: "patient", t: "No." },
      { s: "clinician", t: "Any trouble controlling your bladder or bowels, or any fevers?" },
      { s: "patient", t: "No, nothing like that." },
      { s: "clinician", t: "Okay, let me examine your back. Tell me if this hurts." },
      { s: "clinician", t: "You're tender over the left lower paraspinal muscles. Straight leg raise is positive on the left at about 45 degrees." },
      { s: "clinician", t: "Strength is 5 out of 5 in both legs and reflexes are normal and symmetric." },
      { s: "clinician", t: "This looks like a lumbar strain with some sciatica, and I'm not concerned about anything serious given your exam." },
      { s: "clinician", t: "We don't need an x-ray right now." },
      { s: "clinician", t: "I'm going to prescribe naproxen 500 milligrams twice a day with food for two weeks, and cyclobenzaprine 5 milligrams at bedtime as needed for spasms." },
      { s: "clinician", t: "I'd also like to refer you to physical therapy." },
      { s: "clinician", t: "Try to stay active, use heat on your back, and avoid lifting anything heavy for now." },
      { s: "clinician", t: "If you develop numbness, weakness, or any trouble with your bladder, go to the ER right away." },
      { s: "clinician", t: "Let's follow up in 4 weeks. Any questions?" },
      { s: "patient", t: "Can I keep going to yoga?" },
      { s: "clinician", t: "Gentle stretching is fine, just skip deep forward bends for now." },
    ],
  },
  {
    key: "kim",
    mrn: "100561",
    name: "Daniel Kim",
    dob: "1997-01-09",
    sex: "M",
    pronouns: "he/him",
    language: "en",
    chart: {
      problems: [],
      medications: [],
      allergies: [],
      social: ["Software engineer"],
      priorVisits: [],
    },
    visit: { time: "10:45", type: "new", reason: "Anxiety and trouble sleeping", template: "soap" },
    script: [
      { s: "clinician", t: "Hi Daniel, welcome. What would you like to talk about today?" },
      { s: "patient", t: "I've been feeling anxious all the time for the past three months, and I can't sleep." },
      { s: "clinician", t: "Tell me more about the anxiety." },
      { s: "patient", t: "I'm on edge at work, my mind races at night, and I've had a couple of panic attacks where my heart is racing." },
      { s: "clinician", t: "How is your sleep?" },
      { s: "patient", t: "I have trouble falling asleep, maybe four or five hours a night, and I'm tired during the day." },
      { s: "clinician", t: "Any low mood or losing interest in things you enjoy?" },
      { s: "patient", t: "Sometimes I feel down, but I still enjoy playing basketball on weekends." },
      { s: "clinician", t: "Any thoughts of hurting yourself or that you'd be better off dead?" },
      { s: "patient", t: "No, never." },
      { s: "clinician", t: "How much alcohol do you drink?" },
      { s: "patient", t: "I drink maybe three or four beers on the weekend." },
      { s: "clinician", t: "Any caffeine?" },
      { s: "patient", t: "Probably three or four coffees a day." },
      { s: "clinician", t: "Your blood pressure is 128 over 82 and heart rate is 88." },
      { s: "clinician", t: "You appear anxious but in no distress. Your mood seems anxious with a full range of affect, and your thought process is logical." },
      { s: "clinician", t: "I think this is most consistent with generalized anxiety disorder with associated insomnia." },
      { s: "clinician", t: "I'd like to start sertraline 25 milligrams daily for one week, then increase to 50 milligrams daily." },
      { s: "clinician", t: "I also recommend talk therapy, so I'm going to refer you to behavioral health." },
      { s: "clinician", t: "Try to cut back on caffeine, especially after noon, and keep screens out of the bedroom." },
      { s: "clinician", t: "If you ever have thoughts of hurting yourself, call or text 988 or go to the emergency room." },
      { s: "clinician", t: "Let's follow up in 4 weeks to see how the medication is working. Any questions for me?" },
      { s: "patient", t: "How long until it starts working?" },
      { s: "clinician", t: "Usually two to four weeks, and side effects like mild nausea usually fade in the first week." },
    ],
  },
  {
    key: "ramirez",
    mrn: "100588",
    name: "Sofia Ramirez",
    dob: "2020-05-30",
    sex: "F",
    pronouns: "she/her",
    language: "es",
    chart: {
      immunizations: [
        { name: "Hepatitis B", date: "2020-05-31" }, { name: "Hepatitis B", date: "2020-07-02" }, { name: "Hepatitis B", date: "2020-12-01" },
        { name: "Rotavirus", date: "2020-07-30" }, { name: "Rotavirus", date: "2020-09-30" },
        { name: "DTaP", date: "2020-07-30" }, { name: "DTaP", date: "2020-09-30" }, { name: "DTaP", date: "2020-12-01" }, { name: "DTaP", date: "2021-09-01" },
        { name: "Hib", date: "2020-07-30" }, { name: "Hib", date: "2020-09-30" }, { name: "Hib", date: "2021-06-01" },
        { name: "PCV15", date: "2020-07-30" }, { name: "PCV15", date: "2020-09-30" }, { name: "PCV15", date: "2020-12-01" }, { name: "PCV15", date: "2021-06-01" },
        { name: "IPV", date: "2020-07-30" }, { name: "IPV", date: "2020-09-30" }, { name: "IPV", date: "2021-06-01" },
        { name: "MMR", date: "2021-06-01" }, { name: "Varicella", date: "2021-06-01" },
        { name: "Hepatitis A", date: "2021-06-01" }, { name: "Hepatitis A", date: "2022-01-10" },
        { name: "Influenza vaccine", date: "2025-10-20" },
      ],
      problems: [],
      medications: [],
      allergies: [{ substance: "penicillin", reaction: "rash" }],
      priorVisits: [{ date: "2026-05-28", summary: "Well child check, age 6. Growth normal.", plan: ["Vaccines up to date"] }],
    },
    visit: { time: "11:30", type: "acute", reason: "Ear pain and fever", template: "soap", outputLang: "es" },
    script: [
      { s: "clinician", t: "Hi Sofia, hi mom. I understand she has ear pain?" },
      { s: "patient", t: "Yes, her right ear has been hurting for two days and she keeps pulling at her ear." },
      { s: "clinician", t: "Has she had a fever?" },
      { s: "patient", t: "Yes, a fever of 102 last night. I gave her Tylenol and it helped." },
      { s: "clinician", t: "Any cough or runny nose?" },
      { s: "patient", t: "A runny nose for about a week." },
      { s: "clinician", t: "Any vomiting or diarrhea?" },
      { s: "patient", t: "No." },
      { s: "clinician", t: "Her temperature today is 100.9. Let me take a look in her ears." },
      { s: "clinician", t: "Her right eardrum is red and bulging. The left eardrum looks normal. Throat looks fine and lungs are clear." },
      { s: "clinician", t: "This is a right middle ear infection. Let's start amoxicillin twice a day for 10 days." },
      { s: "patient", t: "Wait, she's allergic to penicillin, she got a rash last time." },
      { s: "clinician", t: "Thank you for telling me. Let's skip the amoxicillin and start azithromycin once a day for 5 days instead." },
      { s: "clinician", t: "You can keep giving Tylenol or ibuprofen for pain and fever." },
      { s: "clinician", t: "If she has a fever over 102 for more than two more days, swelling behind the ear, or seems very sleepy, bring her back right away." },
      { s: "clinician", t: "Let's recheck her ear in 2 weeks. Any questions?" },
      { s: "patient", t: "Can she go to school tomorrow?" },
      { s: "clinician", t: "Once she has no fever for 24 hours, she can go back." },
    ],
  },
  {
    key: "morales",
    mrn: "100603",
    name: "Ana Morales",
    dob: "1954-10-12",
    sex: "F",
    pronouns: "she/her",
    language: "es",
    chart: {
      problems: [{ name: "Chronic obstructive pulmonary disease", icd10: "J44.9", since: "2018" }],
      medications: [{ name: "albuterol", dose: "2 puffs", frequency: "every 4 hours as needed" }, { name: "budesonide-formoterol", dose: "2 puffs", frequency: "twice daily" }],
      allergies: [],
      social: ["Former smoker, 30 pack-years, quit 2015"],
      smoking: "former",
      screenings: [{ name: "FIT", date: "2026-02-10", result: "Negative" }],
      priorVisits: [{ date: "2026-07-02", summary: "COPD follow-up. Stable.", plan: ["Continue Symbicort", "Pneumonia vaccine due"] }],
    },
    visit: { time: "13:00", type: "follow-up", reason: "COPD follow-up (Spanish interpreter)", template: "soap", outputLang: "es" },
    script: [
      { s: "clinician", t: "Hi Mrs. Morales, how has your breathing been since July?", lang: "en" },
      { s: "other", t: "Hola señora Morales, ¿cómo ha estado su respiración desde julio?", lang: "es" },
      { s: "patient", t: "Más o menos. Me falta el aire cuando camino y tengo tos en las mañanas.", lang: "es" },
      { s: "other", t: "So-so. I get short of breath when I walk and I have a cough in the mornings.", lang: "en" },
      { s: "clinician", t: "How often are you using the albuterol rescue inhaler?", lang: "en" },
      { s: "other", t: "¿Con qué frecuencia usa el inhalador de rescate albuterol?", lang: "es" },
      { s: "patient", t: "Lo uso cada cuatro horas, casi todos los días.", lang: "es" },
      { s: "other", t: "She uses it every six hours, almost every day.", lang: "en" },
      { s: "clinician", t: "Any fever or chest pain?", lang: "en" },
      { s: "other", t: "¿Ha tenido fiebre o dolor de pecho?", lang: "es" },
      { s: "patient", t: "No, nada de eso.", lang: "es" },
      { s: "other", t: "No, none of that.", lang: "en" },
      { s: "clinician", t: "Her oxygen is 93 percent today. Let me listen to her lungs.", lang: "en" },
      { s: "clinician", t: "I hear some wheezing on both sides, but no crackles.", lang: "en" },
      { s: "clinician", t: "Her COPD is not well controlled. Let's continue the Symbicort and I'd like to add tiotropium once daily.", lang: "en" },
      { s: "other", t: "Su EPOC no está bien controlado. Vamos a continuar el Symbicort y agregar tiotropio una vez al día.", lang: "es" },
      { s: "clinician", t: "I also want to order a chest x-ray and give the pneumonia vaccine today.", lang: "en" },
      { s: "other", t: "También quiere ordenar una radiografía de pecho y ponerle la vacuna contra la neumonía hoy.", lang: "es" },
      { s: "clinician", t: "If her breathing gets worse or her lips turn blue, go to the emergency room. Follow up in 4 weeks.", lang: "en" },
      { s: "other", t: "Si su respiración empeora o sus labios se ponen azules, vaya a la sala de emergencias. Regrese en 4 semanas.", lang: "es" },
    ],
  },
  {
    key: "reyes",
    mrn: "100714",
    name: "Jordan Reyes",
    dob: "1991-08-22",
    sex: "F",
    pronouns: "she/her",
    language: "en",
    chart: {
      problems: [{ name: "Major depressive disorder, recurrent, moderate", icd10: "F33.1", since: "2024" }],
      medications: [{ name: "sertraline", dose: "100 mg", frequency: "daily" }],
      allergies: [],
      social: ["Works in accounting", "Lives with her partner and daughter"],
      screenings: [{ name: "PHQ-9", date: "2026-09-14", result: "12" }],
      priorVisits: [{ date: "2026-09-14", summary: "Psychotherapy, CBT for depression. PHQ-9 12.", plan: ["Schedule one enjoyable activity daily", "Thought record practice"] }],
    },
    visit: { time: "15:15", type: "follow-up", reason: "Psychotherapy session, depression", template: "bh_psychotherapy" },
    script: [
      { s: "clinician", t: "Hi Jordan, good to see you. How have the past two weeks been?" },
      { s: "patient", t: "Honestly pretty rough. Work has been overwhelming, and I've been staying in bed most of the weekend." },
      { s: "clinician", t: "Last time we talked about scheduling one enjoyable activity each day. How did that go?" },
      { s: "patient", t: "I went for a walk twice and it helped a little, but most days I didn't do it." },
      { s: "clinician", t: "Your PHQ-9 today is 16, up from 12 two weeks ago." },
      { s: "clinician", t: "When things feel this heavy, have you had any thoughts that you'd be better off dead or of hurting yourself?" },
      { s: "patient", t: "Sometimes I think it would be easier if I just didn't wake up, but I would never do anything." },
      { s: "clinician", t: "Have you thought about how you would do it, or made any plan?" },
      { s: "patient", t: "No, no plan at all." },
      { s: "clinician", t: "Do you have any intention of acting on those thoughts?" },
      { s: "patient", t: "No. I have my daughter, I would never leave her." },
      { s: "clinician", t: "Are there any guns or stockpiled medications at home?" },
      { s: "patient", t: "No guns, and my partner keeps my medications." },
      { s: "clinician", t: "Have you ever tried to hurt yourself in the past?" },
      { s: "patient", t: "No, never." },
      { s: "clinician", t: "Let's update your safety plan together. Your warning signs are staying in bed and pulling away from people, and you can call your sister or text 988 if the thoughts get stronger." },
      { s: "clinician", t: "Let's look at the thought that you're failing at everything. What's the evidence for and against it?" },
      { s: "patient", t: "I guess I did finish the big project on time, so maybe not everything." },
      { s: "clinician", t: "This week, let's plan three walks and one call with a friend." },
      { s: "patient", t: "Okay, I can try that. The walks do help." },
      { s: "clinician", t: "You look tired and your affect is constricted, but your thought process is logical and goal directed." },
      { s: "clinician", t: "Your depression is worse right now. Please bring up your sertraline dose with Dr. Chen at your medication visit, and we'll meet again in one week." },
    ],
  },
  {
    key: "porter",
    mrn: "100933",
    name: "Diane Porter",
    dob: "1964-11-30",
    sex: "F",
    pronouns: "she/her",
    language: "en",
    chart: {
      problems: [{ name: "Adenocarcinoma of the sigmoid colon, stage IIIB", icd10: "C18.7", since: "2026" }, { name: "Essential hypertension", icd10: "I10", since: "2018" }],
      medications: [{ name: "amlodipine", dose: "5 mg", frequency: "daily" }, { name: "ondansetron", dose: "8 mg", frequency: "every 8 hours as needed" }],
      allergies: [],
      labs: [{ name: "CEA", value: "1.8 ng/mL", date: "2026-09-14", flag: "normal" }],
      social: ["Never smoker", "High school teacher, on leave during treatment"],
      oncology: {
        diagnosis: "Malignant neoplasm of sigmoid colon",
        icd10: "C18.7",
        stage: "IIIB",
        tnm: "T3 N1b M0",
        biomarkers: ["KRAS wild type", "Microsatellite stable (pMMR)"],
        diagnosedOn: "April 2026",
        regimens: [{ name: "FOLFOX", start: "2026-06-08", cycles: 5, intent: "adjuvant" }],
        toxicityHistory: [{ date: "2026-09-14", cycle: 5, term: "Peripheral sensory neuropathy", grade: 1 }],
        ecogHistory: [{ date: "2026-06-08", score: 0 }],
      },
      priorVisits: [{ date: "2026-09-14", summary: "FOLFOX cycle 5. Grade 1 neuropathy. ECOG 0.", plan: ["Proceed with cycle 6 in 2 weeks", "CBC and CMP before cycle 6"] }],
    },
    visit: { time: "16:00", type: "follow-up", reason: "FOLFOX cycle 6, colon cancer", template: "onc_followup" },
    script: [
      { s: "clinician", t: "Hi Diane, you're here for cycle 6 of FOLFOX for your colon cancer. How did the last two weeks go?" },
      { s: "patient", t: "The numbness in my fingertips is worse. I've been having trouble opening jars and typing on my phone." },
      { s: "patient", t: "The cold sensitivity lasts about five days after each treatment now." },
      { s: "clinician", t: "Any diarrhea or nausea?" },
      { s: "patient", t: "Some diarrhea, maybe 3 loose stools a day for a couple of days, and I'm eating less for the first few days." },
      { s: "clinician", t: "Are you still getting through your day?" },
      { s: "patient", t: "I'm walking every morning, but I can't do heavy yard work like before." },
      { s: "clinician", t: "Your blood pressure is 132 over 78, heart rate 76, and weight is 68 kilograms." },
      { s: "clinician", t: "Your ANC today is 1.2 and platelets are 98, hemoglobin 11.4." },
      { s: "clinician", t: "Your ECOG is 1, and the CT from last week shows no evidence of disease." },
      { s: "clinician", t: "The neuropathy is grade 2 now, so we'll proceed with cycle 6 today but reduce the oxaliplatin by 20 percent." },
      { s: "clinician", t: "Let's continue the ondansetron as needed for nausea, and use loperamide for the diarrhea." },
      { s: "clinician", t: "Call us for a fever of 100.4 or higher, or more than 6 stools a day. Follow up in 2 weeks for cycle 7." },
    ],
  },
];
export interface InpatientDemo {
  mrn: string;
  name: string;
  dob: string;
  sex: "F" | "M";
  pronouns: string;
  chart: Chart;
  reason: string;
  unit: string;
  room: string;
  scripts: { hp: DemoLine[]; day2: DemoLine[]; day3: DemoLine[]; discharge: DemoLine[] };
}

export const INPATIENT_DEMO: InpatientDemo = {
  mrn: "200731",
  name: "Harold Jensen",
  dob: "1952-04-18",
  sex: "M",
  pronouns: "he/him",
  reason: "Acute on chronic heart failure exacerbation",
  unit: "4 West",
  room: "412",
  chart: {
    problems: [
      { name: "Chronic diastolic heart failure", icd10: "I50.32", since: "2021" },
      { name: "Atrial fibrillation", icd10: "I48.91", since: "2019" },
      { name: "Chronic kidney disease, stage 3a", icd10: "N18.31", since: "2022" },
      { name: "Essential hypertension", icd10: "I10", since: "2010" },
    ],
    medications: [
      { name: "furosemide", dose: "40 mg", frequency: "daily" },
      { name: "apixaban", dose: "5 mg", frequency: "twice daily" },
      { name: "metoprolol succinate", dose: "50 mg", frequency: "daily" },
      { name: "lisinopril", dose: "10 mg", frequency: "daily" },
    ],
    allergies: [],
    vitals: { Weight: "88 kg", BP: "136/80" },
    labs: [{ name: "Creatinine", value: "1.2 mg/dL", date: "2026-08-20", flag: "high" }],
    egfr: 58,
    coverage: { payer: "Medicare", plan: "Medicare Part A and B", memberId: "1EG4TE5MK31" },
    social: ["Former smoker, quit 2000", "Lives with his wife"],
    smoking: "former",
  },
  scripts: {
    hp: [
      { s: "clinician", t: "Mr. Jensen, I'm the hospitalist taking care of you. What brought you in tonight?" },
      { s: "patient", t: "I've been getting more short of breath over the last week, and my legs are swollen. I can't lie flat, so I've been sleeping in the recliner." },
      { s: "clinician", t: "Any chest pain?" },
      { s: "patient", t: "No, no chest pain." },
      { s: "clinician", t: "Have you been taking your furosemide?" },
      { s: "patient", t: "I ran out of the furosemide about ten days ago, and we had a lot of takeout." },
      { s: "clinician", t: "Your oxygen is 91 percent on room air, blood pressure is 158 over 88, and your heart rate is 96. You weigh 94 kilograms, up from your usual 88." },
      { s: "clinician", t: "Your BNP is 1450, creatinine is 1.4, and the chest x-ray shows pulmonary edema." },
      { s: "clinician", t: "I hear crackles at both lung bases, and you have 2 plus pitting edema up to the knees." },
      { s: "clinician", t: "This is an acute on chronic heart failure exacerbation, likely from missing the furosemide and extra salt." },
      { s: "clinician", t: "We'll give IV furosemide 40 milligrams twice a day, limit salt to 2 grams, check a basic metabolic panel every morning, and get an echocardiogram." },
      { s: "clinician", t: "Your atrial fibrillation rate is controlled, so continue apixaban 5 milligrams twice a day and metoprolol." },
      { s: "clinician", t: "We'll hold the lisinopril while we diurese and watch your kidney function." },
    ],
    day2: [
      { s: "clinician", t: "Good morning Mr. Jensen, how was your night?" },
      { s: "patient", t: "Much better. I slept in the bed with two pillows, and I've been peeing a lot." },
      { s: "clinician", t: "Any shortness of breath at rest?" },
      { s: "patient", t: "No, only when I walk to the bathroom." },
      { s: "clinician", t: "You're down 2 kilograms, weight is 92 kilograms this morning. Oxygen is 95 percent on room air and blood pressure is 138 over 78." },
      { s: "clinician", t: "Creatinine is 1.5, a small bump, and potassium is 3.6." },
      { s: "clinician", t: "The crackles are less, and the swelling is down to your shins." },
      { s: "clinician", t: "The echocardiogram shows an ejection fraction of 55 percent, so this is heart failure with preserved ejection fraction." },
      { s: "clinician", t: "Your heart failure is improving. Continue IV furosemide 40 milligrams twice a day, and start potassium chloride 20 milligrams daily." },
      { s: "clinician", t: "Your atrial fibrillation is rate controlled; continue apixaban and metoprolol." },
    ],
    day3: [
      { s: "clinician", t: "How are you feeling today?" },
      { s: "patient", t: "Almost back to normal. I walked the hallway twice this morning." },
      { s: "clinician", t: "Weight is 90 kilograms, down another 2. Oxygen is 97 percent on room air, and blood pressure is 128 over 74." },
      { s: "clinician", t: "Creatinine is back to 1.3, and potassium is 4.1." },
      { s: "clinician", t: "Your lungs are clear now, and there is only trace swelling at the ankles." },
      { s: "clinician", t: "Your heart failure is much better. Let's switch to oral furosemide 40 milligrams daily and plan for discharge tomorrow if your weight holds." },
    ],
    discharge: [
      { s: "clinician", t: "You're ready to go home today. Your weight is 89.5 kilograms this morning." },
      { s: "clinician", t: "Take furosemide 40 milligrams every morning, keep taking apixaban and metoprolol, and continue potassium chloride 20 milligrams daily." },
      { s: "clinician", t: "Restart the lisinopril 10 milligrams daily now that your kidney function is back to baseline." },
      { s: "clinician", t: "Weigh yourself every morning and keep salt under 2 grams a day." },
      { s: "clinician", t: "Follow up with cardiology in 1 week and get a basic metabolic panel in 3 days." },
      { s: "patient", t: "Okay. What if I get short of breath again?" },
      { s: "clinician", t: "Call us if you gain more than 2 pounds in a day or 5 pounds in a week. Come back to the emergency room if you're short of breath at rest, have chest pain, or feel faint." },
    ],
  },
};

export const NURSING_DEMO = [
  "0800 assessment. Blood pressure 128 over 74, heart rate 72, resp rate 16, temp 98.2, sats 97 percent on room air. Weight 90 kg. Alert and oriented times four. Lungs clear. Trace edema at the ankles. Pain is 2 out of 10 in the lower back. Skin intact, Braden 19. 20 gauge IV in the left forearm, site clean dry and intact. Drank 480 mL, ate 75 percent of breakfast, voided 600 mL. Morse 35, bed alarm on. Ambulated 150 feet with standby assist. 2 gram sodium diet. Educated on daily weights and fluid restriction, and he verbalized understanding. Needs the IV removed before discharge. Recheck potassium at noon.",
  "1200 update. Potassium drawn and sent. Blood pressure 124 over 70, heart rate 70. Ate 100 percent of lunch. Voided 400 mL. Wife at bedside, reviewed low salt food choices with her.",
];

export const ED_DEMO = {
  mrn: "300418",
  name: "Marcus Hill",
  dob: "1968-02-11",
  sex: "M" as const,
  pronouns: "he/him",
  room: "ED 7",
  complaint: "Chest pain",
  chart: {
    problems: [{ name: "Essential hypertension", icd10: "I10" }, { name: "Hyperlipidemia", icd10: "E78.5" }],
    medications: [{ name: "amlodipine", dose: "5 mg", frequency: "daily" }, { name: "atorvastatin", dose: "40 mg", frequency: "daily" }],
    allergies: [],
    coverage: { payer: "Commercial" as const, plan: "Aetna PPO", memberId: "W300418" },
  } as Chart,
  script: [
    { s: "clinician" as const, t: "Hi Mr. Hill, I'm the emergency physician. What brought you in?" },
    { s: "patient" as const, t: "I had pressure in the middle of my chest for about 30 minutes while I was shoveling, and it went away when I sat down." },
    { s: "clinician" as const, t: "Does it spread anywhere, and did you have shortness of breath or sweating?" },
    { s: "patient" as const, t: "A little into my left arm, and I was sweaty. No trouble breathing now." },
    { s: "clinician" as const, t: "Your blood pressure is 158 over 92, heart rate 84, and oxygen is 98 percent." },
    { s: "clinician" as const, t: "Your heart sounds regular with no murmurs, and your lungs are clear." },
    { s: "clinician" as const, t: "The first ECG shows normal sinus rhythm without ST changes, and the first troponin is under 5." },
    { s: "clinician" as const, t: "I'm concerned about unstable angina, so we'll give aspirin 324 milligrams, get a chest x-ray, and repeat the troponin in two hours." },
    { s: "clinician" as const, t: "Re-evaluating now after the aspirin, you're pain free and the repeat ECG is unchanged." },
    { s: "clinician" as const, t: "The repeat troponin is still under 5, and the chest x-ray shows no acute findings." },
    { s: "clinician" as const, t: "Your HEART score is 4, which is moderate risk, so I'm going to admit you to the observation unit for a stress test in the morning." },
  ],
};
